package HadithOnto;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Verse <br>
 * @version generated on Thu Jan 10 15:58:46 PKT 2019 by Bushra
 */

public interface Verse extends WrappedIndividual {

    /* ***************************************************
     * Property http://quranontology.com/Resource/mentionedIn
     */
     
    /**
     * Gets all property values for the mentionedIn property.<p>
     * 
     * @returns a collection of values for the mentionedIn property.
     */
    Collection<? extends Hadith> getMentionedIn();

    /**
     * Checks if the class has a mentionedIn property value.<p>
     * 
     * @return true if there is a mentionedIn property value.
     */
    boolean hasMentionedIn();

    /**
     * Adds a mentionedIn property value.<p>
     * 
     * @param newMentionedIn the mentionedIn property value to be added
     */
    void addMentionedIn(Hadith newMentionedIn);

    /**
     * Removes a mentionedIn property value.<p>
     * 
     * @param oldMentionedIn the mentionedIn property value to be removed.
     */
    void removeMentionedIn(Hadith oldMentionedIn);


    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#assertedBy
     */
     
    /**
     * Gets all property values for the assertedBy property.<p>
     * 
     * @returns a collection of values for the assertedBy property.
     */
    Collection<? extends WrappedIndividual> getAssertedBy();

    /**
     * Checks if the class has a assertedBy property value.<p>
     * 
     * @return true if there is a assertedBy property value.
     */
    boolean hasAssertedBy();

    /**
     * Adds a assertedBy property value.<p>
     * 
     * @param newAssertedBy the assertedBy property value to be added
     */
    void addAssertedBy(WrappedIndividual newAssertedBy);

    /**
     * Removes a assertedBy property value.<p>
     * 
     * @param oldAssertedBy the assertedBy property value to be removed.
     */
    void removeAssertedBy(WrappedIndividual oldAssertedBy);


    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#asserts
     */
     
    /**
     * Gets all property values for the asserts property.<p>
     * 
     * @returns a collection of values for the asserts property.
     */
    Collection<? extends WrappedIndividual> getAsserts();

    /**
     * Checks if the class has a asserts property value.<p>
     * 
     * @return true if there is a asserts property value.
     */
    boolean hasAsserts();

    /**
     * Adds a asserts property value.<p>
     * 
     * @param newAsserts the asserts property value to be added
     */
    void addAsserts(WrappedIndividual newAsserts);

    /**
     * Removes a asserts property value.<p>
     * 
     * @param oldAsserts the asserts property value to be removed.
     */
    void removeAsserts(WrappedIndividual oldAsserts);


    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#authored
     */
     
    /**
     * Gets all property values for the authored property.<p>
     * 
     * @returns a collection of values for the authored property.
     */
    Collection<? extends WrappedIndividual> getAuthored();

    /**
     * Checks if the class has a authored property value.<p>
     * 
     * @return true if there is a authored property value.
     */
    boolean hasAuthored();

    /**
     * Adds a authored property value.<p>
     * 
     * @param newAuthored the authored property value to be added
     */
    void addAuthored(WrappedIndividual newAuthored);

    /**
     * Removes a authored property value.<p>
     * 
     * @param oldAuthored the authored property value to be removed.
     */
    void removeAuthored(WrappedIndividual oldAuthored);


    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#authoredBy
     */
     
    /**
     * Gets all property values for the authoredBy property.<p>
     * 
     * @returns a collection of values for the authoredBy property.
     */
    Collection<? extends WrappedIndividual> getAuthoredBy();

    /**
     * Checks if the class has a authoredBy property value.<p>
     * 
     * @return true if there is a authoredBy property value.
     */
    boolean hasAuthoredBy();

    /**
     * Adds a authoredBy property value.<p>
     * 
     * @param newAuthoredBy the authoredBy property value to be added
     */
    void addAuthoredBy(WrappedIndividual newAuthoredBy);

    /**
     * Removes a authoredBy property value.<p>
     * 
     * @param oldAuthoredBy the authoredBy property value to be removed.
     */
    void removeAuthoredBy(WrappedIndividual oldAuthoredBy);


    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#happenedIn
     */
     
    /**
     * Gets all property values for the happenedIn property.<p>
     * 
     * @returns a collection of values for the happenedIn property.
     */
    Collection<? extends WrappedIndividual> getHappenedIn();

    /**
     * Checks if the class has a happenedIn property value.<p>
     * 
     * @return true if there is a happenedIn property value.
     */
    boolean hasHappenedIn();

    /**
     * Adds a happenedIn property value.<p>
     * 
     * @param newHappenedIn the happenedIn property value to be added
     */
    void addHappenedIn(WrappedIndividual newHappenedIn);

    /**
     * Removes a happenedIn property value.<p>
     * 
     * @param oldHappenedIn the happenedIn property value to be removed.
     */
    void removeHappenedIn(WrappedIndividual oldHappenedIn);


    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hasPart
     */
     
    /**
     * Gets all property values for the hasPart property.<p>
     * 
     * @returns a collection of values for the hasPart property.
     */
    Collection<? extends WrappedIndividual> getHasPart();

    /**
     * Checks if the class has a hasPart property value.<p>
     * 
     * @return true if there is a hasPart property value.
     */
    boolean hasHasPart();

    /**
     * Adds a hasPart property value.<p>
     * 
     * @param newHasPart the hasPart property value to be added
     */
    void addHasPart(WrappedIndividual newHasPart);

    /**
     * Removes a hasPart property value.<p>
     * 
     * @param oldHasPart the hasPart property value to be removed.
     */
    void removeHasPart(WrappedIndividual oldHasPart);


    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#involvedIn
     */
     
    /**
     * Gets all property values for the involvedIn property.<p>
     * 
     * @returns a collection of values for the involvedIn property.
     */
    Collection<? extends WrappedIndividual> getInvolvedIn();

    /**
     * Checks if the class has a involvedIn property value.<p>
     * 
     * @return true if there is a involvedIn property value.
     */
    boolean hasInvolvedIn();

    /**
     * Adds a involvedIn property value.<p>
     * 
     * @param newInvolvedIn the involvedIn property value to be added
     */
    void addInvolvedIn(WrappedIndividual newInvolvedIn);

    /**
     * Removes a involvedIn property value.<p>
     * 
     * @param oldInvolvedIn the involvedIn property value to be removed.
     */
    void removeInvolvedIn(WrappedIndividual oldInvolvedIn);


    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#isPartOf
     */
     
    /**
     * Gets all property values for the isPartOf property.<p>
     * 
     * @returns a collection of values for the isPartOf property.
     */
    Collection<? extends WrappedIndividual> getIsPartOf();

    /**
     * Checks if the class has a isPartOf property value.<p>
     * 
     * @return true if there is a isPartOf property value.
     */
    boolean hasIsPartOf();

    /**
     * Adds a isPartOf property value.<p>
     * 
     * @param newIsPartOf the isPartOf property value to be added
     */
    void addIsPartOf(WrappedIndividual newIsPartOf);

    /**
     * Removes a isPartOf property value.<p>
     * 
     * @param oldIsPartOf the isPartOf property value to be removed.
     */
    void removeIsPartOf(WrappedIndividual oldIsPartOf);


    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#participatedIn
     */
     
    /**
     * Gets all property values for the participatedIn property.<p>
     * 
     * @returns a collection of values for the participatedIn property.
     */
    Collection<? extends WrappedIndividual> getParticipatedIn();

    /**
     * Checks if the class has a participatedIn property value.<p>
     * 
     * @return true if there is a participatedIn property value.
     */
    boolean hasParticipatedIn();

    /**
     * Adds a participatedIn property value.<p>
     * 
     * @param newParticipatedIn the participatedIn property value to be added
     */
    void addParticipatedIn(WrappedIndividual newParticipatedIn);

    /**
     * Removes a participatedIn property value.<p>
     * 
     * @param oldParticipatedIn the participatedIn property value to be removed.
     */
    void removeParticipatedIn(WrappedIndividual oldParticipatedIn);


    /* ***************************************************
     * Property https://www.w3.org/1999/02/22-rdf-syntax-ns#seeAlso
     */
     
    /**
     * Gets all property values for the seeAlso property.<p>
     * 
     * @returns a collection of values for the seeAlso property.
     */
    Collection<? extends WrappedIndividual> getSeeAlso();

    /**
     * Checks if the class has a seeAlso property value.<p>
     * 
     * @return true if there is a seeAlso property value.
     */
    boolean hasSeeAlso();

    /**
     * Adds a seeAlso property value.<p>
     * 
     * @param newSeeAlso the seeAlso property value to be added
     */
    void addSeeAlso(WrappedIndividual newSeeAlso);

    /**
     * Removes a seeAlso property value.<p>
     * 
     * @param oldSeeAlso the seeAlso property value to be removed.
     */
    void removeSeeAlso(WrappedIndividual oldSeeAlso);


    /* ***************************************************
     * Property http://mlode.nlp2rdf.org/quranvocab#chapterIndex
     */
     
    /**
     * Gets all property values for the chapterIndex property.<p>
     * 
     * @returns a collection of values for the chapterIndex property.
     */
    Collection<? extends Object> getChapterIndex();

    /**
     * Checks if the class has a chapterIndex property value.<p>
     * 
     * @return true if there is a chapterIndex property value.
     */
    boolean hasChapterIndex();

    /**
     * Adds a chapterIndex property value.<p>
     * 
     * @param newChapterIndex the chapterIndex property value to be added
     */
    void addChapterIndex(Object newChapterIndex);

    /**
     * Removes a chapterIndex property value.<p>
     * 
     * @param oldChapterIndex the chapterIndex property value to be removed.
     */
    void removeChapterIndex(Object oldChapterIndex);



    /* ***************************************************
     * Property http://mlode.nlp2rdf.org/quranvocab#verseIndex
     */
     
    /**
     * Gets all property values for the verseIndex property.<p>
     * 
     * @returns a collection of values for the verseIndex property.
     */
    Collection<? extends Object> getVerseIndex();

    /**
     * Checks if the class has a verseIndex property value.<p>
     * 
     * @return true if there is a verseIndex property value.
     */
    boolean hasVerseIndex();

    /**
     * Adds a verseIndex property value.<p>
     * 
     * @param newVerseIndex the verseIndex property value to be added
     */
    void addVerseIndex(Object newVerseIndex);

    /**
     * Removes a verseIndex property value.<p>
     * 
     * @param oldVerseIndex the verseIndex property value to be removed.
     */
    void removeVerseIndex(Object oldVerseIndex);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#akhtalatTadlees
     */
     
    /**
     * Gets all property values for the akhtalatTadlees property.<p>
     * 
     * @returns a collection of values for the akhtalatTadlees property.
     */
    Collection<? extends Object> getAkhtalatTadlees();

    /**
     * Checks if the class has a akhtalatTadlees property value.<p>
     * 
     * @return true if there is a akhtalatTadlees property value.
     */
    boolean hasAkhtalatTadlees();

    /**
     * Adds a akhtalatTadlees property value.<p>
     * 
     * @param newAkhtalatTadlees the akhtalatTadlees property value to be added
     */
    void addAkhtalatTadlees(Object newAkhtalatTadlees);

    /**
     * Removes a akhtalatTadlees property value.<p>
     * 
     * @param oldAkhtalatTadlees the akhtalatTadlees property value to be removed.
     */
    void removeAkhtalatTadlees(Object oldAkhtalatTadlees);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#alAqama
     */
     
    /**
     * Gets all property values for the alAqama property.<p>
     * 
     * @returns a collection of values for the alAqama property.
     */
    Collection<? extends Object> getAlAqama();

    /**
     * Checks if the class has a alAqama property value.<p>
     * 
     * @return true if there is a alAqama property value.
     */
    boolean hasAlAqama();

    /**
     * Adds a alAqama property value.<p>
     * 
     * @param newAlAqama the alAqama property value to be added
     */
    void addAlAqama(Object newAlAqama);

    /**
     * Removes a alAqama property value.<p>
     * 
     * @param oldAlAqama the alAqama property value to be removed.
     */
    void removeAlAqama(Object oldAlAqama);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#alMawali
     */
     
    /**
     * Gets all property values for the alMawali property.<p>
     * 
     * @returns a collection of values for the alMawali property.
     */
    Collection<? extends Object> getAlMawali();

    /**
     * Checks if the class has a alMawali property value.<p>
     * 
     * @return true if there is a alMawali property value.
     */
    boolean hasAlMawali();

    /**
     * Adds a alMawali property value.<p>
     * 
     * @param newAlMawali the alMawali property value to be added
     */
    void addAlMawali(Object newAlMawali);

    /**
     * Removes a alMawali property value.<p>
     * 
     * @param oldAlMawali the alMawali property value to be removed.
     */
    void removeAlMawali(Object oldAlMawali);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#anNishat
     */
     
    /**
     * Gets all property values for the anNishat property.<p>
     * 
     * @returns a collection of values for the anNishat property.
     */
    Collection<? extends Object> getAnNishat();

    /**
     * Checks if the class has a anNishat property value.<p>
     * 
     * @return true if there is a anNishat property value.
     */
    boolean hasAnNishat();

    /**
     * Adds a anNishat property value.<p>
     * 
     * @param newAnNishat the anNishat property value to be added
     */
    void addAnNishat(Object newAnNishat);

    /**
     * Removes a anNishat property value.<p>
     * 
     * @param oldAnNishat the anNishat property value to be removed.
     */
    void removeAnNishat(Object oldAnNishat);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#baladAlWafat
     */
     
    /**
     * Gets all property values for the baladAlWafat property.<p>
     * 
     * @returns a collection of values for the baladAlWafat property.
     */
    Collection<? extends Object> getBaladAlWafat();

    /**
     * Checks if the class has a baladAlWafat property value.<p>
     * 
     * @return true if there is a baladAlWafat property value.
     */
    boolean hasBaladAlWafat();

    /**
     * Adds a baladAlWafat property value.<p>
     * 
     * @param newBaladAlWafat the baladAlWafat property value to be added
     */
    void addBaladAlWafat(Object newBaladAlWafat);

    /**
     * Removes a baladAlWafat property value.<p>
     * 
     * @param oldBaladAlWafat the baladAlWafat property value to be removed.
     */
    void removeBaladAlWafat(Object oldBaladAlWafat);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#chapterTarjama
     */
     
    /**
     * Gets all property values for the chapterTarjama property.<p>
     * 
     * @returns a collection of values for the chapterTarjama property.
     */
    Collection<? extends Object> getChapterTarjama();

    /**
     * Checks if the class has a chapterTarjama property value.<p>
     * 
     * @return true if there is a chapterTarjama property value.
     */
    boolean hasChapterTarjama();

    /**
     * Adds a chapterTarjama property value.<p>
     * 
     * @param newChapterTarjama the chapterTarjama property value to be added
     */
    void addChapterTarjama(Object newChapterTarjama);

    /**
     * Removes a chapterTarjama property value.<p>
     * 
     * @param oldChapterTarjama the chapterTarjama property value to be removed.
     */
    void removeChapterTarjama(Object oldChapterTarjama);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#collectionName
     */
     
    /**
     * Gets all property values for the collectionName property.<p>
     * 
     * @returns a collection of values for the collectionName property.
     */
    Collection<? extends Object> getCollectionName();

    /**
     * Checks if the class has a collectionName property value.<p>
     * 
     * @return true if there is a collectionName property value.
     */
    boolean hasCollectionName();

    /**
     * Adds a collectionName property value.<p>
     * 
     * @param newCollectionName the collectionName property value to be added
     */
    void addCollectionName(Object newCollectionName);

    /**
     * Removes a collectionName property value.<p>
     * 
     * @param oldCollectionName the collectionName property value to be removed.
     */
    void removeCollectionName(Object oldCollectionName);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#date
     */
     
    /**
     * Gets all property values for the date property.<p>
     * 
     * @returns a collection of values for the date property.
     */
    Collection<? extends Object> getDate();

    /**
     * Checks if the class has a date property value.<p>
     * 
     * @return true if there is a date property value.
     */
    boolean hasDate();

    /**
     * Adds a date property value.<p>
     * 
     * @param newDate the date property value to be added
     */
    void addDate(Object newDate);

    /**
     * Removes a date property value.<p>
     * 
     * @param oldDate the date property value to be removed.
     */
    void removeDate(Object oldDate);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#deprecatedHadithNo
     */
     
    /**
     * Gets all property values for the deprecatedHadithNo property.<p>
     * 
     * @returns a collection of values for the deprecatedHadithNo property.
     */
    Collection<? extends Object> getDeprecatedHadithNo();

    /**
     * Checks if the class has a deprecatedHadithNo property value.<p>
     * 
     * @return true if there is a deprecatedHadithNo property value.
     */
    boolean hasDeprecatedHadithNo();

    /**
     * Adds a deprecatedHadithNo property value.<p>
     * 
     * @param newDeprecatedHadithNo the deprecatedHadithNo property value to be added
     */
    void addDeprecatedHadithNo(Object newDeprecatedHadithNo);

    /**
     * Removes a deprecatedHadithNo property value.<p>
     * 
     * @param oldDeprecatedHadithNo the deprecatedHadithNo property value to be removed.
     */
    void removeDeprecatedHadithNo(Object oldDeprecatedHadithNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#eBookNo
     */
     
    /**
     * Gets all property values for the eBookNo property.<p>
     * 
     * @returns a collection of values for the eBookNo property.
     */
    Collection<? extends Object> getEBookNo();

    /**
     * Checks if the class has a eBookNo property value.<p>
     * 
     * @return true if there is a eBookNo property value.
     */
    boolean hasEBookNo();

    /**
     * Adds a eBookNo property value.<p>
     * 
     * @param newEBookNo the eBookNo property value to be added
     */
    void addEBookNo(Object newEBookNo);

    /**
     * Removes a eBookNo property value.<p>
     * 
     * @param oldEBookNo the eBookNo property value to be removed.
     */
    void removeEBookNo(Object oldEBookNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#eHadithNo
     */
     
    /**
     * Gets all property values for the eHadithNo property.<p>
     * 
     * @returns a collection of values for the eHadithNo property.
     */
    Collection<? extends Object> getEHadithNo();

    /**
     * Checks if the class has a eHadithNo property value.<p>
     * 
     * @return true if there is a eHadithNo property value.
     */
    boolean hasEHadithNo();

    /**
     * Adds a eHadithNo property value.<p>
     * 
     * @param newEHadithNo the eHadithNo property value to be added
     */
    void addEHadithNo(Object newEHadithNo);

    /**
     * Removes a eHadithNo property value.<p>
     * 
     * @param oldEHadithNo the eHadithNo property value to be removed.
     */
    void removeEHadithNo(Object oldEHadithNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#eVolNo
     */
     
    /**
     * Gets all property values for the eVolNo property.<p>
     * 
     * @returns a collection of values for the eVolNo property.
     */
    Collection<? extends Object> getEVolNo();

    /**
     * Checks if the class has a eVolNo property value.<p>
     * 
     * @return true if there is a eVolNo property value.
     */
    boolean hasEVolNo();

    /**
     * Adds a eVolNo property value.<p>
     * 
     * @param newEVolNo the eVolNo property value to be added
     */
    void addEVolNo(Object newEVolNo);

    /**
     * Removes a eVolNo property value.<p>
     * 
     * @param oldEVolNo the eVolNo property value to be removed.
     */
    void removeEVolNo(Object oldEVolNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#endingHadithNo
     */
     
    /**
     * Gets all property values for the endingHadithNo property.<p>
     * 
     * @returns a collection of values for the endingHadithNo property.
     */
    Collection<? extends Object> getEndingHadithNo();

    /**
     * Checks if the class has a endingHadithNo property value.<p>
     * 
     * @return true if there is a endingHadithNo property value.
     */
    boolean hasEndingHadithNo();

    /**
     * Adds a endingHadithNo property value.<p>
     * 
     * @param newEndingHadithNo the endingHadithNo property value to be added
     */
    void addEndingHadithNo(Object newEndingHadithNo);

    /**
     * Removes a endingHadithNo property value.<p>
     * 
     * @param oldEndingHadithNo the endingHadithNo property value to be removed.
     */
    void removeEndingHadithNo(Object oldEndingHadithNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#englishReference
     */
     
    /**
     * Gets all property values for the englishReference property.<p>
     * 
     * @returns a collection of values for the englishReference property.
     */
    Collection<? extends Object> getEnglishReference();

    /**
     * Checks if the class has a englishReference property value.<p>
     * 
     * @return true if there is a englishReference property value.
     */
    boolean hasEnglishReference();

    /**
     * Adds a englishReference property value.<p>
     * 
     * @param newEnglishReference the englishReference property value to be added
     */
    void addEnglishReference(Object newEnglishReference);

    /**
     * Removes a englishReference property value.<p>
     * 
     * @param oldEnglishReference the englishReference property value to be removed.
     */
    void removeEnglishReference(Object oldEnglishReference);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#firstChar
     */
     
    /**
     * Gets all property values for the firstChar property.<p>
     * 
     * @returns a collection of values for the firstChar property.
     */
    Collection<? extends Object> getFirstChar();

    /**
     * Checks if the class has a firstChar property value.<p>
     * 
     * @return true if there is a firstChar property value.
     */
    boolean hasFirstChar();

    /**
     * Adds a firstChar property value.<p>
     * 
     * @param newFirstChar the firstChar property value to be added
     */
    void addFirstChar(Object newFirstChar);

    /**
     * Removes a firstChar property value.<p>
     * 
     * @param oldFirstChar the firstChar property value to be removed.
     */
    void removeFirstChar(Object oldFirstChar);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#fullHadith
     */
     
    /**
     * Gets all property values for the fullHadith property.<p>
     * 
     * @returns a collection of values for the fullHadith property.
     */
    Collection<? extends Object> getFullHadith();

    /**
     * Checks if the class has a fullHadith property value.<p>
     * 
     * @return true if there is a fullHadith property value.
     */
    boolean hasFullHadith();

    /**
     * Adds a fullHadith property value.<p>
     * 
     * @param newFullHadith the fullHadith property value to be added
     */
    void addFullHadith(Object newFullHadith);

    /**
     * Removes a fullHadith property value.<p>
     * 
     * @param oldFullHadith the fullHadith property value to be removed.
     */
    void removeFullHadith(Object oldFullHadith);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookIntro
     */
     
    /**
     * Gets all property values for the hadithBookIntro property.<p>
     * 
     * @returns a collection of values for the hadithBookIntro property.
     */
    Collection<? extends Object> getHadithBookIntro();

    /**
     * Checks if the class has a hadithBookIntro property value.<p>
     * 
     * @return true if there is a hadithBookIntro property value.
     */
    boolean hasHadithBookIntro();

    /**
     * Adds a hadithBookIntro property value.<p>
     * 
     * @param newHadithBookIntro the hadithBookIntro property value to be added
     */
    void addHadithBookIntro(Object newHadithBookIntro);

    /**
     * Removes a hadithBookIntro property value.<p>
     * 
     * @param oldHadithBookIntro the hadithBookIntro property value to be removed.
     */
    void removeHadithBookIntro(Object oldHadithBookIntro);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookNo
     */
     
    /**
     * Gets all property values for the hadithBookNo property.<p>
     * 
     * @returns a collection of values for the hadithBookNo property.
     */
    Collection<? extends Object> getHadithBookNo();

    /**
     * Checks if the class has a hadithBookNo property value.<p>
     * 
     * @return true if there is a hadithBookNo property value.
     */
    boolean hasHadithBookNo();

    /**
     * Adds a hadithBookNo property value.<p>
     * 
     * @param newHadithBookNo the hadithBookNo property value to be added
     */
    void addHadithBookNo(Object newHadithBookNo);

    /**
     * Removes a hadithBookNo property value.<p>
     * 
     * @param oldHadithBookNo the hadithBookNo property value to be removed.
     */
    void removeHadithBookNo(Object oldHadithBookNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookUrl
     */
     
    /**
     * Gets all property values for the hadithBookUrl property.<p>
     * 
     * @returns a collection of values for the hadithBookUrl property.
     */
    Collection<? extends Object> getHadithBookUrl();

    /**
     * Checks if the class has a hadithBookUrl property value.<p>
     * 
     * @return true if there is a hadithBookUrl property value.
     */
    boolean hasHadithBookUrl();

    /**
     * Adds a hadithBookUrl property value.<p>
     * 
     * @param newHadithBookUrl the hadithBookUrl property value to be added
     */
    void addHadithBookUrl(Object newHadithBookUrl);

    /**
     * Removes a hadithBookUrl property value.<p>
     * 
     * @param oldHadithBookUrl the hadithBookUrl property value to be removed.
     */
    void removeHadithBookUrl(Object oldHadithBookUrl);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithChapterNo
     */
     
    /**
     * Gets all property values for the hadithChapterNo property.<p>
     * 
     * @returns a collection of values for the hadithChapterNo property.
     */
    Collection<? extends Object> getHadithChapterNo();

    /**
     * Checks if the class has a hadithChapterNo property value.<p>
     * 
     * @return true if there is a hadithChapterNo property value.
     */
    boolean hasHadithChapterNo();

    /**
     * Adds a hadithChapterNo property value.<p>
     * 
     * @param newHadithChapterNo the hadithChapterNo property value to be added
     */
    void addHadithChapterNo(Object newHadithChapterNo);

    /**
     * Removes a hadithChapterNo property value.<p>
     * 
     * @param oldHadithChapterNo the hadithChapterNo property value to be removed.
     */
    void removeHadithChapterNo(Object oldHadithChapterNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithNo
     */
     
    /**
     * Gets all property values for the hadithNo property.<p>
     * 
     * @returns a collection of values for the hadithNo property.
     */
    Collection<? extends Object> getHadithNo();

    /**
     * Checks if the class has a hadithNo property value.<p>
     * 
     * @return true if there is a hadithNo property value.
     */
    boolean hasHadithNo();

    /**
     * Adds a hadithNo property value.<p>
     * 
     * @param newHadithNo the hadithNo property value to be added
     */
    void addHadithNo(Object newHadithNo);

    /**
     * Removes a hadithNo property value.<p>
     * 
     * @param oldHadithNo the hadithNo property value to be removed.
     */
    void removeHadithNo(Object oldHadithNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithReferenceNo
     */
     
    /**
     * Gets all property values for the hadithReferenceNo property.<p>
     * 
     * @returns a collection of values for the hadithReferenceNo property.
     */
    Collection<? extends Object> getHadithReferenceNo();

    /**
     * Checks if the class has a hadithReferenceNo property value.<p>
     * 
     * @return true if there is a hadithReferenceNo property value.
     */
    boolean hasHadithReferenceNo();

    /**
     * Adds a hadithReferenceNo property value.<p>
     * 
     * @param newHadithReferenceNo the hadithReferenceNo property value to be added
     */
    void addHadithReferenceNo(Object newHadithReferenceNo);

    /**
     * Removes a hadithReferenceNo property value.<p>
     * 
     * @param oldHadithReferenceNo the hadithReferenceNo property value to be removed.
     */
    void removeHadithReferenceNo(Object oldHadithReferenceNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithRepetition
     */
     
    /**
     * Gets all property values for the hadithRepetition property.<p>
     * 
     * @returns a collection of values for the hadithRepetition property.
     */
    Collection<? extends Object> getHadithRepetition();

    /**
     * Checks if the class has a hadithRepetition property value.<p>
     * 
     * @return true if there is a hadithRepetition property value.
     */
    boolean hasHadithRepetition();

    /**
     * Adds a hadithRepetition property value.<p>
     * 
     * @param newHadithRepetition the hadithRepetition property value to be added
     */
    void addHadithRepetition(Object newHadithRepetition);

    /**
     * Removes a hadithRepetition property value.<p>
     * 
     * @param oldHadithRepetition the hadithRepetition property value to be removed.
     */
    void removeHadithRepetition(Object oldHadithRepetition);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithText
     */
     
    /**
     * Gets all property values for the hadithText property.<p>
     * 
     * @returns a collection of values for the hadithText property.
     */
    Collection<? extends Object> getHadithText();

    /**
     * Checks if the class has a hadithText property value.<p>
     * 
     * @return true if there is a hadithText property value.
     */
    boolean hasHadithText();

    /**
     * Adds a hadithText property value.<p>
     * 
     * @param newHadithText the hadithText property value to be added
     */
    void addHadithText(Object newHadithText);

    /**
     * Removes a hadithText property value.<p>
     * 
     * @param oldHadithText the hadithText property value to be removed.
     */
    void removeHadithText(Object oldHadithText);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithType
     */
     
    /**
     * Gets all property values for the hadithType property.<p>
     * 
     * @returns a collection of values for the hadithType property.
     */
    Collection<? extends Object> getHadithType();

    /**
     * Checks if the class has a hadithType property value.<p>
     * 
     * @return true if there is a hadithType property value.
     */
    boolean hasHadithType();

    /**
     * Adds a hadithType property value.<p>
     * 
     * @param newHadithType the hadithType property value to be added
     */
    void addHadithType(Object newHadithType);

    /**
     * Removes a hadithType property value.<p>
     * 
     * @param oldHadithType the hadithType property value to be removed.
     */
    void removeHadithType(Object oldHadithType);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithUrl
     */
     
    /**
     * Gets all property values for the hadithUrl property.<p>
     * 
     * @returns a collection of values for the hadithUrl property.
     */
    Collection<? extends Object> getHadithUrl();

    /**
     * Checks if the class has a hadithUrl property value.<p>
     * 
     * @return true if there is a hadithUrl property value.
     */
    boolean hasHadithUrl();

    /**
     * Adds a hadithUrl property value.<p>
     * 
     * @param newHadithUrl the hadithUrl property value to be added
     */
    void addHadithUrl(Object newHadithUrl);

    /**
     * Removes a hadithUrl property value.<p>
     * 
     * @param oldHadithUrl the hadithUrl property value to be removed.
     */
    void removeHadithUrl(Object oldHadithUrl);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithVolumeNo
     */
     
    /**
     * Gets all property values for the hadithVolumeNo property.<p>
     * 
     * @returns a collection of values for the hadithVolumeNo property.
     */
    Collection<? extends Object> getHadithVolumeNo();

    /**
     * Checks if the class has a hadithVolumeNo property value.<p>
     * 
     * @return true if there is a hadithVolumeNo property value.
     */
    boolean hasHadithVolumeNo();

    /**
     * Adds a hadithVolumeNo property value.<p>
     * 
     * @param newHadithVolumeNo the hadithVolumeNo property value to be added
     */
    void addHadithVolumeNo(Object newHadithVolumeNo);

    /**
     * Removes a hadithVolumeNo property value.<p>
     * 
     * @param oldHadithVolumeNo the hadithVolumeNo property value to be removed.
     */
    void removeHadithVolumeNo(Object oldHadithVolumeNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#inBookNo
     */
     
    /**
     * Gets all property values for the inBookNo property.<p>
     * 
     * @returns a collection of values for the inBookNo property.
     */
    Collection<? extends Object> getInBookNo();

    /**
     * Checks if the class has a inBookNo property value.<p>
     * 
     * @return true if there is a inBookNo property value.
     */
    boolean hasInBookNo();

    /**
     * Adds a inBookNo property value.<p>
     * 
     * @param newInBookNo the inBookNo property value to be added
     */
    void addInBookNo(Object newInBookNo);

    /**
     * Removes a inBookNo property value.<p>
     * 
     * @param oldInBookNo the inBookNo property value to be removed.
     */
    void removeInBookNo(Object oldInBookNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#ismArRavi
     */
     
    /**
     * Gets all property values for the ismArRavi property.<p>
     * 
     * @returns a collection of values for the ismArRavi property.
     */
    Collection<? extends Object> getIsmArRavi();

    /**
     * Checks if the class has a ismArRavi property value.<p>
     * 
     * @return true if there is a ismArRavi property value.
     */
    boolean hasIsmArRavi();

    /**
     * Adds a ismArRavi property value.<p>
     * 
     * @param newIsmArRavi the ismArRavi property value to be added
     */
    void addIsmArRavi(Object newIsmArRavi);

    /**
     * Removes a ismArRavi property value.<p>
     * 
     * @param oldIsmArRavi the ismArRavi property value to be removed.
     */
    void removeIsmArRavi(Object oldIsmArRavi);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#ismAsSuhra
     */
     
    /**
     * Gets all property values for the ismAsSuhra property.<p>
     * 
     * @returns a collection of values for the ismAsSuhra property.
     */
    Collection<? extends Object> getIsmAsSuhra();

    /**
     * Checks if the class has a ismAsSuhra property value.<p>
     * 
     * @return true if there is a ismAsSuhra property value.
     */
    boolean hasIsmAsSuhra();

    /**
     * Adds a ismAsSuhra property value.<p>
     * 
     * @param newIsmAsSuhra the ismAsSuhra property value to be added
     */
    void addIsmAsSuhra(Object newIsmAsSuhra);

    /**
     * Removes a ismAsSuhra property value.<p>
     * 
     * @param oldIsmAsSuhra the ismAsSuhra property value to be removed.
     */
    void removeIsmAsSuhra(Object oldIsmAsSuhra);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#kunyat
     */
     
    /**
     * Gets all property values for the kunyat property.<p>
     * 
     * @returns a collection of values for the kunyat property.
     */
    Collection<? extends Object> getKunyat();

    /**
     * Checks if the class has a kunyat property value.<p>
     * 
     * @return true if there is a kunyat property value.
     */
    boolean hasKunyat();

    /**
     * Adds a kunyat property value.<p>
     * 
     * @param newKunyat the kunyat property value to be added
     */
    void addKunyat(Object newKunyat);

    /**
     * Removes a kunyat property value.<p>
     * 
     * @param oldKunyat the kunyat property value to be removed.
     */
    void removeKunyat(Object oldKunyat);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#laqab
     */
     
    /**
     * Gets all property values for the laqab property.<p>
     * 
     * @returns a collection of values for the laqab property.
     */
    Collection<? extends Object> getLaqab();

    /**
     * Checks if the class has a laqab property value.<p>
     * 
     * @return true if there is a laqab property value.
     */
    boolean hasLaqab();

    /**
     * Adds a laqab property value.<p>
     * 
     * @param newLaqab the laqab property value to be added
     */
    void addLaqab(Object newLaqab);

    /**
     * Removes a laqab property value.<p>
     * 
     * @param oldLaqab the laqab property value to be removed.
     */
    void removeLaqab(Object oldLaqab);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#mazhab
     */
     
    /**
     * Gets all property values for the mazhab property.<p>
     * 
     * @returns a collection of values for the mazhab property.
     */
    Collection<? extends Object> getMazhab();

    /**
     * Checks if the class has a mazhab property value.<p>
     * 
     * @return true if there is a mazhab property value.
     */
    boolean hasMazhab();

    /**
     * Adds a mazhab property value.<p>
     * 
     * @param newMazhab the mazhab property value to be added
     */
    void addMazhab(Object newMazhab);

    /**
     * Removes a mazhab property value.<p>
     * 
     * @param oldMazhab the mazhab property value to be removed.
     */
    void removeMazhab(Object oldMazhab);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#name
     */
     
    /**
     * Gets all property values for the name property.<p>
     * 
     * @returns a collection of values for the name property.
     */
    Collection<? extends Object> getName();

    /**
     * Checks if the class has a name property value.<p>
     * 
     * @return true if there is a name property value.
     */
    boolean hasName();

    /**
     * Adds a name property value.<p>
     * 
     * @param newName the name property value to be added
     */
    void addName(Object newName);

    /**
     * Removes a name property value.<p>
     * 
     * @param oldName the name property value to be removed.
     */
    void removeName(Object oldName);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#narratorChain
     */
     
    /**
     * Gets all property values for the narratorChain property.<p>
     * 
     * @returns a collection of values for the narratorChain property.
     */
    Collection<? extends Object> getNarratorChain();

    /**
     * Checks if the class has a narratorChain property value.<p>
     * 
     * @return true if there is a narratorChain property value.
     */
    boolean hasNarratorChain();

    /**
     * Adds a narratorChain property value.<p>
     * 
     * @param newNarratorChain the narratorChain property value to be added
     */
    void addNarratorChain(Object newNarratorChain);

    /**
     * Removes a narratorChain property value.<p>
     * 
     * @param oldNarratorChain the narratorChain property value to be removed.
     */
    void removeNarratorChain(Object oldNarratorChain);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#nasab
     */
     
    /**
     * Gets all property values for the nasab property.<p>
     * 
     * @returns a collection of values for the nasab property.
     */
    Collection<? extends Object> getNasab();

    /**
     * Checks if the class has a nasab property value.<p>
     * 
     * @return true if there is a nasab property value.
     */
    boolean hasNasab();

    /**
     * Adds a nasab property value.<p>
     * 
     * @param newNasab the nasab property value to be added
     */
    void addNasab(Object newNasab);

    /**
     * Removes a nasab property value.<p>
     * 
     * @param oldNasab the nasab property value to be removed.
     */
    void removeNasab(Object oldNasab);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#raqamArRavi
     */
     
    /**
     * Gets all property values for the raqamArRavi property.<p>
     * 
     * @returns a collection of values for the raqamArRavi property.
     */
    Collection<? extends Object> getRaqamArRavi();

    /**
     * Checks if the class has a raqamArRavi property value.<p>
     * 
     * @return true if there is a raqamArRavi property value.
     */
    boolean hasRaqamArRavi();

    /**
     * Adds a raqamArRavi property value.<p>
     * 
     * @param newRaqamArRavi the raqamArRavi property value to be added
     */
    void addRaqamArRavi(Object newRaqamArRavi);

    /**
     * Removes a raqamArRavi property value.<p>
     * 
     * @param oldRaqamArRavi the raqamArRavi property value to be removed.
     */
    void removeRaqamArRavi(Object oldRaqamArRavi);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#rutba
     */
     
    /**
     * Gets all property values for the rutba property.<p>
     * 
     * @returns a collection of values for the rutba property.
     */
    Collection<? extends Object> getRutba();

    /**
     * Checks if the class has a rutba property value.<p>
     * 
     * @return true if there is a rutba property value.
     */
    boolean hasRutba();

    /**
     * Adds a rutba property value.<p>
     * 
     * @param newRutba the rutba property value to be added
     */
    void addRutba(Object newRutba);

    /**
     * Removes a rutba property value.<p>
     * 
     * @param oldRutba the rutba property value to be removed.
     */
    void removeRutba(Object oldRutba);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#sameAs
     */
     
    /**
     * Gets all property values for the sameAs property.<p>
     * 
     * @returns a collection of values for the sameAs property.
     */
    Collection<? extends Object> getSameAs();

    /**
     * Checks if the class has a sameAs property value.<p>
     * 
     * @return true if there is a sameAs property value.
     */
    boolean hasSameAs();

    /**
     * Adds a sameAs property value.<p>
     * 
     * @param newSameAs the sameAs property value to be added
     */
    void addSameAs(Object newSameAs);

    /**
     * Removes a sameAs property value.<p>
     * 
     * @param oldSameAs the sameAs property value to be removed.
     */
    void removeSameAs(Object oldSameAs);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#sequenceNo
     */
     
    /**
     * Gets all property values for the sequenceNo property.<p>
     * 
     * @returns a collection of values for the sequenceNo property.
     */
    Collection<? extends Object> getSequenceNo();

    /**
     * Checks if the class has a sequenceNo property value.<p>
     * 
     * @return true if there is a sequenceNo property value.
     */
    boolean hasSequenceNo();

    /**
     * Adds a sequenceNo property value.<p>
     * 
     * @param newSequenceNo the sequenceNo property value to be added
     */
    void addSequenceNo(Object newSequenceNo);

    /**
     * Removes a sequenceNo property value.<p>
     * 
     * @param oldSequenceNo the sequenceNo property value to be removed.
     */
    void removeSequenceNo(Object oldSequenceNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#startingHadithNo
     */
     
    /**
     * Gets all property values for the startingHadithNo property.<p>
     * 
     * @returns a collection of values for the startingHadithNo property.
     */
    Collection<? extends Object> getStartingHadithNo();

    /**
     * Checks if the class has a startingHadithNo property value.<p>
     * 
     * @return true if there is a startingHadithNo property value.
     */
    boolean hasStartingHadithNo();

    /**
     * Adds a startingHadithNo property value.<p>
     * 
     * @param newStartingHadithNo the startingHadithNo property value to be added
     */
    void addStartingHadithNo(Object newStartingHadithNo);

    /**
     * Removes a startingHadithNo property value.<p>
     * 
     * @param oldStartingHadithNo the startingHadithNo property value to be removed.
     */
    void removeStartingHadithNo(Object oldStartingHadithNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#sunAlMilad
     */
     
    /**
     * Gets all property values for the sunAlMilad property.<p>
     * 
     * @returns a collection of values for the sunAlMilad property.
     */
    Collection<? extends Object> getSunAlMilad();

    /**
     * Checks if the class has a sunAlMilad property value.<p>
     * 
     * @return true if there is a sunAlMilad property value.
     */
    boolean hasSunAlMilad();

    /**
     * Adds a sunAlMilad property value.<p>
     * 
     * @param newSunAlMilad the sunAlMilad property value to be added
     */
    void addSunAlMilad(Object newSunAlMilad);

    /**
     * Removes a sunAlMilad property value.<p>
     * 
     * @param oldSunAlMilad the sunAlMilad property value to be removed.
     */
    void removeSunAlMilad(Object oldSunAlMilad);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#sunAlWafat
     */
     
    /**
     * Gets all property values for the sunAlWafat property.<p>
     * 
     * @returns a collection of values for the sunAlWafat property.
     */
    Collection<? extends Object> getSunAlWafat();

    /**
     * Checks if the class has a sunAlWafat property value.<p>
     * 
     * @return true if there is a sunAlWafat property value.
     */
    boolean hasSunAlWafat();

    /**
     * Adds a sunAlWafat property value.<p>
     * 
     * @param newSunAlWafat the sunAlWafat property value to be added
     */
    void addSunAlWafat(Object newSunAlWafat);

    /**
     * Removes a sunAlWafat property value.<p>
     * 
     * @param oldSunAlWafat the sunAlWafat property value to be removed.
     */
    void removeSunAlWafat(Object oldSunAlWafat);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#taqba
     */
     
    /**
     * Gets all property values for the taqba property.<p>
     * 
     * @returns a collection of values for the taqba property.
     */
    Collection<? extends Object> getTaqba();

    /**
     * Checks if the class has a taqba property value.<p>
     * 
     * @return true if there is a taqba property value.
     */
    boolean hasTaqba();

    /**
     * Adds a taqba property value.<p>
     * 
     * @param newTaqba the taqba property value to be added
     */
    void addTaqba(Object newTaqba);

    /**
     * Removes a taqba property value.<p>
     * 
     * @param oldTaqba the taqba property value to be removed.
     */
    void removeTaqba(Object oldTaqba);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#totalHadithInchapter
     */
     
    /**
     * Gets all property values for the totalHadithInchapter property.<p>
     * 
     * @returns a collection of values for the totalHadithInchapter property.
     */
    Collection<? extends Object> getTotalHadithInchapter();

    /**
     * Checks if the class has a totalHadithInchapter property value.<p>
     * 
     * @return true if there is a totalHadithInchapter property value.
     */
    boolean hasTotalHadithInchapter();

    /**
     * Adds a totalHadithInchapter property value.<p>
     * 
     * @param newTotalHadithInchapter the totalHadithInchapter property value to be added
     */
    void addTotalHadithInchapter(Object newTotalHadithInchapter);

    /**
     * Removes a totalHadithInchapter property value.<p>
     * 
     * @param oldTotalHadithInchapter the totalHadithInchapter property value to be removed.
     */
    void removeTotalHadithInchapter(Object oldTotalHadithInchapter);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#totalSubChapters
     */
     
    /**
     * Gets all property values for the totalSubChapters property.<p>
     * 
     * @returns a collection of values for the totalSubChapters property.
     */
    Collection<? extends Object> getTotalSubChapters();

    /**
     * Checks if the class has a totalSubChapters property value.<p>
     * 
     * @return true if there is a totalSubChapters property value.
     */
    boolean hasTotalSubChapters();

    /**
     * Adds a totalSubChapters property value.<p>
     * 
     * @param newTotalSubChapters the totalSubChapters property value to be added
     */
    void addTotalSubChapters(Object newTotalSubChapters);

    /**
     * Removes a totalSubChapters property value.<p>
     * 
     * @param oldTotalSubChapters the totalSubChapters property value to be removed.
     */
    void removeTotalSubChapters(Object oldTotalSubChapters);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#ummarArRavi
     */
     
    /**
     * Gets all property values for the ummarArRavi property.<p>
     * 
     * @returns a collection of values for the ummarArRavi property.
     */
    Collection<? extends Object> getUmmarArRavi();

    /**
     * Checks if the class has a ummarArRavi property value.<p>
     * 
     * @return true if there is a ummarArRavi property value.
     */
    boolean hasUmmarArRavi();

    /**
     * Adds a ummarArRavi property value.<p>
     * 
     * @param newUmmarArRavi the ummarArRavi property value to be added
     */
    void addUmmarArRavi(Object newUmmarArRavi);

    /**
     * Removes a ummarArRavi property value.<p>
     * 
     * @param oldUmmarArRavi the ummarArRavi property value to be removed.
     */
    void removeUmmarArRavi(Object oldUmmarArRavi);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#wasaf
     */
     
    /**
     * Gets all property values for the wasaf property.<p>
     * 
     * @returns a collection of values for the wasaf property.
     */
    Collection<? extends Object> getWasaf();

    /**
     * Checks if the class has a wasaf property value.<p>
     * 
     * @return true if there is a wasaf property value.
     */
    boolean hasWasaf();

    /**
     * Adds a wasaf property value.<p>
     * 
     * @param newWasaf the wasaf property value to be added
     */
    void addWasaf(Object newWasaf);

    /**
     * Removes a wasaf property value.<p>
     * 
     * @param oldWasaf the wasaf property value to be removed.
     */
    void removeWasaf(Object oldWasaf);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc##gradedBy
     */
     
    /**
     * Gets all property values for the gradedBy property.<p>
     * 
     * @returns a collection of values for the gradedBy property.
     */
    Collection<? extends Object> getGradedBy();

    /**
     * Checks if the class has a gradedBy property value.<p>
     * 
     * @return true if there is a gradedBy property value.
     */
    boolean hasGradedBy();

    /**
     * Adds a gradedBy property value.<p>
     * 
     * @param newGradedBy the gradedBy property value to be added
     */
    void addGradedBy(Object newGradedBy);

    /**
     * Removes a gradedBy property value.<p>
     * 
     * @param oldGradedBy the gradedBy property value to be removed.
     */
    void removeGradedBy(Object oldGradedBy);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc##hadithGrade
     */
     
    /**
     * Gets all property values for the hadithGrade property.<p>
     * 
     * @returns a collection of values for the hadithGrade property.
     */
    Collection<? extends Object> getHadithGrade();

    /**
     * Checks if the class has a hadithGrade property value.<p>
     * 
     * @return true if there is a hadithGrade property value.
     */
    boolean hasHadithGrade();

    /**
     * Adds a hadithGrade property value.<p>
     * 
     * @param newHadithGrade the hadithGrade property value to be added
     */
    void addHadithGrade(Object newHadithGrade);

    /**
     * Removes a hadithGrade property value.<p>
     * 
     * @param oldHadithGrade the hadithGrade property value to be removed.
     */
    void removeHadithGrade(Object oldHadithGrade);



    /* ***************************************************
     * Property https://www.w3.org/2000/01/rdf-schema#label
     */
     
    /**
     * Gets all property values for the label property.<p>
     * 
     * @returns a collection of values for the label property.
     */
    Collection<? extends Object> getLabel();

    /**
     * Checks if the class has a label property value.<p>
     * 
     * @return true if there is a label property value.
     */
    boolean hasLabel();

    /**
     * Adds a label property value.<p>
     * 
     * @param newLabel the label property value to be added
     */
    void addLabel(Object newLabel);

    /**
     * Removes a label property value.<p>
     * 
     * @param oldLabel the label property value to be removed.
     */
    void removeLabel(Object oldLabel);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
