package HadithOnto;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Mon Nov 19 14:39:18 PKT 2018 by Bushra
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://mlode.nlp2rdf.org/quranvocab#Verse
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VERSE.<p>
     * 
     */
    public static final OWLClass CLASS_VERSE = factory.getOWLClass(IRI.create("http://mlode.nlp2rdf.org/quranvocab#Verse"));

    /* ***************************************************
     * Class http://quranontology.com/Resource/City
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CITY.<p>
     * 
     */
    public static final OWLClass CLASS_CITY = factory.getOWLClass(IRI.create("http://quranontology.com/Resource/City"));

    /* ***************************************************
     * Class http://quranontology.com/Resource/HistoricEvent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HISTORICEVENT.<p>
     * 
     */
    public static final OWLClass CLASS_HISTORICEVENT = factory.getOWLClass(IRI.create("http://quranontology.com/Resource/HistoricEvent"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#AfterLifeEvent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AFTERLIFEEVENT.<p>
     * 
     */
    public static final OWLClass CLASS_AFTERLIFEEVENT = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#AfterLifeEvent"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Angel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANGEL.<p>
     * 
     */
    public static final OWLClass CLASS_ANGEL = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Angel"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Animal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANIMAL.<p>
     * 
     */
    public static final OWLClass CLASS_ANIMAL = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Animal"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Assertion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ASSERTION.<p>
     * 
     */
    public static final OWLClass CLASS_ASSERTION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Assertion"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#BadriCompanion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BADRICOMPANION.<p>
     * 
     */
    public static final OWLClass CLASS_BADRICOMPANION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#BadriCompanion"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Believer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BELIEVER.<p>
     * 
     */
    public static final OWLClass CLASS_BELIEVER = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Believer"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Birth
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BIRTH.<p>
     * 
     */
    public static final OWLClass CLASS_BIRTH = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Birth"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Companion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPANION.<p>
     * 
     */
    public static final OWLClass CLASS_COMPANION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Companion"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#ConversionToIslam
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONVERSIONTOISLAM.<p>
     * 
     */
    public static final OWLClass CLASS_CONVERSIONTOISLAM = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#ConversionToIslam"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Death
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEATH.<p>
     * 
     */
    public static final OWLClass CLASS_DEATH = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Death"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Delegation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DELEGATION.<p>
     * 
     */
    public static final OWLClass CLASS_DELEGATION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Delegation"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#DivineLocation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DIVINELOCATION.<p>
     * 
     */
    public static final OWLClass CLASS_DIVINELOCATION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#DivineLocation"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Divorce
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DIVORCE.<p>
     * 
     */
    public static final OWLClass CLASS_DIVORCE = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Divorce"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Event
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EVENT.<p>
     * 
     */
    public static final OWLClass CLASS_EVENT = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Event"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#GeographicalLocation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GEOGRAPHICALLOCATION.<p>
     * 
     */
    public static final OWLClass CLASS_GEOGRAPHICALLOCATION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#GeographicalLocation"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Ghazwa
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GHAZWA.<p>
     * 
     */
    public static final OWLClass CLASS_GHAZWA = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Ghazwa"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#GodPunishment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GODPUNISHMENT.<p>
     * 
     */
    public static final OWLClass CLASS_GODPUNISHMENT = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#GodPunishment"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Hadith
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITH.<p>
     * 
     */
    public static final OWLClass CLASS_HADITH = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Hadith"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithBook
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHBOOK.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHBOOK = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithBook"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithChapter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHCHAPTER.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHCHAPTER = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithChapter"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithCollection
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHCOLLECTION.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHCOLLECTION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithCollection"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithCollectionAuthor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHCOLLECTIONAUTHOR.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHCOLLECTIONAUTHOR = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithCollectionAuthor"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithMatan
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHMATAN.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHMATAN = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithMatan"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithNarrator
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHNARRATOR.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHNARRATOR = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithNarrator"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithSanad
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHSANAD.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHSANAD = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithSanad"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Heaven
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HEAVEN.<p>
     * 
     */
    public static final OWLClass CLASS_HEAVEN = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Heaven"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Hell
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HELL.<p>
     * 
     */
    public static final OWLClass CLASS_HELL = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Hell"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HistoricPerson
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HISTORICPERSON.<p>
     * 
     */
    public static final OWLClass CLASS_HISTORICPERSON = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HistoricPerson"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Human
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HUMAN.<p>
     * 
     */
    public static final OWLClass CLASS_HUMAN = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Human"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Jinn
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class JINN.<p>
     * 
     */
    public static final OWLClass CLASS_JINN = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Jinn"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Journey
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class JOURNEY.<p>
     * 
     */
    public static final OWLClass CLASS_JOURNEY = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Journey"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#LandmarksOrHistoricalBuildings
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LANDMARKSORHISTORICALBUILDINGS.<p>
     * 
     */
    public static final OWLClass CLASS_LANDMARKSORHISTORICALBUILDINGS = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#LandmarksOrHistoricalBuildings"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#LivingCreation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LIVINGCREATION.<p>
     * 
     */
    public static final OWLClass CLASS_LIVINGCREATION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#LivingCreation"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Marriage
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MARRIAGE.<p>
     * 
     */
    public static final OWLClass CLASS_MARRIAGE = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Marriage"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Migration
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MIGRATION.<p>
     * 
     */
    public static final OWLClass CLASS_MIGRATION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Migration"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#MilitaryConflict
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MILITARYCONFLICT.<p>
     * 
     */
    public static final OWLClass CLASS_MILITARYCONFLICT = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#MilitaryConflict"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Miracle
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MIRACLE.<p>
     * 
     */
    public static final OWLClass CLASS_MIRACLE = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Miracle"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Mountain
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MOUNTAIN.<p>
     * 
     */
    public static final OWLClass CLASS_MOUNTAIN = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Mountain"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#NonBeliever
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NONBELIEVER.<p>
     * 
     */
    public static final OWLClass CLASS_NONBELIEVER = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#NonBeliever"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Person"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Place
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLACE.<p>
     * 
     */
    public static final OWLClass CLASS_PLACE = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Place"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Prediction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PREDICTION.<p>
     * 
     */
    public static final OWLClass CLASS_PREDICTION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Prediction"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Prophet
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROPHET.<p>
     * 
     */
    public static final OWLClass CLASS_PROPHET = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Prophet"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Revelation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REVELATION.<p>
     * 
     */
    public static final OWLClass CLASS_REVELATION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Revelation"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#River
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RIVER.<p>
     * 
     */
    public static final OWLClass CLASS_RIVER = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#River"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#RootNarrrator
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROOTNARRRATOR.<p>
     * 
     */
    public static final OWLClass CLASS_ROOTNARRRATOR = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#RootNarrrator"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Sea
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SEA.<p>
     * 
     */
    public static final OWLClass CLASS_SEA = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Sea"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#TradeJourney
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TRADEJOURNEY.<p>
     * 
     */
    public static final OWLClass CLASS_TRADEJOURNEY = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#TradeJourney"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Tribe
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TRIBE.<p>
     * 
     */
    public static final OWLClass CLASS_TRIBE = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Tribe"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc##GroupOfPeople
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GROUPOFPEOPLE.<p>
     * 
     */
    public static final OWLClass CLASS_GROUPOFPEOPLE = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc##GroupOfPeople"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc'#AfterlifeLocation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AFTERLIFELOCATION.<p>
     * 
     */
    public static final OWLClass CLASS_AFTERLIFELOCATION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc'#AfterlifeLocation"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/containsMentionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINSMENTIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINSMENTIONOF = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/containsMentionOf"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/mentionedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MENTIONEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MENTIONEDIN = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/mentionedIn"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#assertedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ASSERTEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ASSERTEDBY = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#assertedBy"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#asserts
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ASSERTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ASSERTS = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#asserts"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#authored
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property AUTHORED.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_AUTHORED = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#authored"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#authoredBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property AUTHOREDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_AUTHOREDBY = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#authoredBy"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#happenedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAPPENEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAPPENEDIN = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#happenedIn"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasPart
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPART.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPART = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasPart"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#involvedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVOLVEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVOLVEDIN = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#involvedIn"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#isPartOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOF = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#isPartOf"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#narrated
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property NARRATED.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_NARRATED = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#narrated"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#narratedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property NARRATEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_NARRATEDBY = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#narratedBy"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#participatedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PARTICIPATEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PARTICIPATEDIN = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#participatedIn"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#chapterIndex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHAPTERINDEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHAPTERINDEX = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#chapterIndex"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#verseIndex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VERSEINDEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VERSEINDEX = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#verseIndex"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#akhtalatTadlees
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property AKHTALATTADLEES.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_AKHTALATTADLEES = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#akhtalatTadlees"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#alAqama
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ALAQAMA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ALAQAMA = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#alAqama"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#alMawali
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ALMAWALI.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ALMAWALI = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#alMawali"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#anNishat
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ANNISHAT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ANNISHAT = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#anNishat"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#baladAlWafat
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BALADALWAFAT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BALADALWAFAT = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#baladAlWafat"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#chapterTarjama
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHAPTERTARJAMA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHAPTERTARJAMA = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#chapterTarjama"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#collectionName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COLLECTIONNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COLLECTIONNAME = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#collectionName"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#date
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DATE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#date"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#deprecatedHadithNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEPRECATEDHADITHNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEPRECATEDHADITHNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#deprecatedHadithNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#eBookNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property EBOOKNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_EBOOKNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#eBookNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#eHadithNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property EHADITHNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_EHADITHNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#eHadithNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#eVolNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property EVOLNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_EVOLNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#eVolNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#endingHadithNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENDINGHADITHNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENDINGHADITHNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#endingHadithNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#englishReference
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENGLISHREFERENCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENGLISHREFERENCE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#englishReference"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#firstChar
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FIRSTCHAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FIRSTCHAR = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#firstChar"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#fullHadith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FULLHADITH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FULLHADITH = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#fullHadith"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookIntro
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHBOOKINTRO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHBOOKINTRO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithBookIntro"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHBOOKNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHBOOKNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithBookNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookUrl
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHBOOKURL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHBOOKURL = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithBookUrl"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithChapterNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHCHAPTERNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHCHAPTERNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithChapterNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithReferenceNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHREFERENCENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHREFERENCENO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithReferenceNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithRepetition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHREPETITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHREPETITION = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithRepetition"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithText
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHTEXT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHTEXT = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithText"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHTYPE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithType"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithUrl
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHURL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHURL = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithUrl"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithVolumeNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHVOLUMENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHVOLUMENO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithVolumeNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#inBookNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INBOOKNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INBOOKNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#inBookNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#ismArRavi
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISMARRAVI.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISMARRAVI = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#ismArRavi"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#ismAsSuhra
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISMASSUHRA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISMASSUHRA = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#ismAsSuhra"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#kunyat
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property KUNYAT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_KUNYAT = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#kunyat"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#laqab
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LAQAB.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LAQAB = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#laqab"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#mazhab
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MAZHAB.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MAZHAB = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#mazhab"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NAME = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#name"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#narratorChain
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NARRATORCHAIN.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NARRATORCHAIN = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#narratorChain"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#nasab
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NASAB.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NASAB = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#nasab"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#raqamArRavi
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RAQAMARRAVI.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RAQAMARRAVI = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#raqamArRavi"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#rutba
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RUTBA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RUTBA = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#rutba"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#sameAs
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SAMEAS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SAMEAS = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#sameAs"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#sequenceNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SEQUENCENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SEQUENCENO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#sequenceNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#startingHadithNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STARTINGHADITHNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STARTINGHADITHNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#startingHadithNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#sunAlMilad
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SUNALMILAD.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SUNALMILAD = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#sunAlMilad"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#sunAlWafat
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SUNALWAFAT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SUNALWAFAT = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#sunAlWafat"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#taqba
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TAQBA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TAQBA = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#taqba"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#totalHadithInchapter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOTALHADITHINCHAPTER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TOTALHADITHINCHAPTER = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#totalHadithInchapter"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#totalSubChapters
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOTALSUBCHAPTERS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TOTALSUBCHAPTERS = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#totalSubChapters"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#ummarArRavi
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property UMMARARRAVI.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_UMMARARRAVI = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#ummarArRavi"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#wasaf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WASAF.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WASAF = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#wasaf"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc##gradedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GRADEDBY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GRADEDBY = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc##gradedBy"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc##hadithGrade
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHGRADE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHGRADE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc##hadithGrade"));

    /* ***************************************************
     * Data Property https://www.w3.org/2000/01/rdf-schema#label
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LABEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LABEL = factory.getOWLDataProperty(IRI.create("https://www.w3.org/2000/01/rdf-schema#label"));


}
