package HadithRDFconvertor;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Hadith <br>
 * @version generated on Mon Aug 08 23:13:12 PKT 2016 by Bushra
 */

public interface Hadith extends WrappedIndividual {

    /* ***************************************************
     * Property http://purl.org/dc/terms/hasPart
     */
     
    /**
     * Gets all property values for the hasPart property.<p>
     * 
     * @returns a collection of values for the hasPart property.
     */
    Collection<? extends WrappedIndividual> getHasPart();

    /**
     * Checks if the class has a hasPart property value.<p>
     * 
     * @return true if there is a hasPart property value.
     */
    boolean hasHasPart();

    /**
     * Adds a hasPart property value.<p>
     * 
     * @param newHasPart the hasPart property value to be added
     */
    void addHasPart(WrappedIndividual newHasPart);

    /**
     * Removes a hasPart property value.<p>
     * 
     * @param oldHasPart the hasPart property value to be removed.
     */
    void removeHasPart(WrappedIndividual oldHasPart);


    /* ***************************************************
     * Property http://purl.org/dc/terms/isPartOf
     */
     
    /**
     * Gets all property values for the isPartOf property.<p>
     * 
     * @returns a collection of values for the isPartOf property.
     */
    Collection<? extends WrappedIndividual> getIsPartOf();

    /**
     * Checks if the class has a isPartOf property value.<p>
     * 
     * @return true if there is a isPartOf property value.
     */
    boolean hasIsPartOf();

    /**
     * Adds a isPartOf property value.<p>
     * 
     * @param newIsPartOf the isPartOf property value to be added
     */
    void addIsPartOf(WrappedIndividual newIsPartOf);

    /**
     * Removes a isPartOf property value.<p>
     * 
     * @param oldIsPartOf the isPartOf property value to be removed.
     */
    void removeIsPartOf(WrappedIndividual oldIsPartOf);


    /* ***************************************************
     * Property http://quranontology.com/Resource/ContainsMentionOf
     */
     
    /**
     * Gets all property values for the ContainsMentionOf property.<p>
     * 
     * @returns a collection of values for the ContainsMentionOf property.
     */
    Collection<? extends WrappedIndividual> getContainsMentionOf();

    /**
     * Checks if the class has a ContainsMentionOf property value.<p>
     * 
     * @return true if there is a ContainsMentionOf property value.
     */
    boolean hasContainsMentionOf();

    /**
     * Adds a ContainsMentionOf property value.<p>
     * 
     * @param newContainsMentionOf the ContainsMentionOf property value to be added
     */
    void addContainsMentionOf(WrappedIndividual newContainsMentionOf);

    /**
     * Removes a ContainsMentionOf property value.<p>
     * 
     * @param oldContainsMentionOf the ContainsMentionOf property value to be removed.
     */
    void removeContainsMentionOf(WrappedIndividual oldContainsMentionOf);


    /* ***************************************************
     * Property http://quranontology.com/Resource/MentionedIn
     */
     
    /**
     * Gets all property values for the MentionedIn property.<p>
     * 
     * @returns a collection of values for the MentionedIn property.
     */
    Collection<? extends Hadith> getMentionedIn();

    /**
     * Checks if the class has a MentionedIn property value.<p>
     * 
     * @return true if there is a MentionedIn property value.
     */
    boolean hasMentionedIn();

    /**
     * Adds a MentionedIn property value.<p>
     * 
     * @param newMentionedIn the MentionedIn property value to be added
     */
    void addMentionedIn(Hadith newMentionedIn);

    /**
     * Removes a MentionedIn property value.<p>
     * 
     * @param oldMentionedIn the MentionedIn property value to be removed.
     */
    void removeMentionedIn(Hadith oldMentionedIn);


    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#collectionName
     */
     
    /**
     * Gets all property values for the collectionName property.<p>
     * 
     * @returns a collection of values for the collectionName property.
     */
    Collection<? extends Object> getCollectionName();

    /**
     * Checks if the class has a collectionName property value.<p>
     * 
     * @return true if there is a collectionName property value.
     */
    boolean hasCollectionName();

    /**
     * Adds a collectionName property value.<p>
     * 
     * @param newCollectionName the collectionName property value to be added
     */
    void addCollectionName(Object newCollectionName);

    /**
     * Removes a collectionName property value.<p>
     * 
     * @param oldCollectionName the collectionName property value to be removed.
     */
    void removeCollectionName(Object oldCollectionName);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#deprecatedBookNo
     */
     
    /**
     * Gets all property values for the deprecatedBookNo property.<p>
     * 
     * @returns a collection of values for the deprecatedBookNo property.
     */
    Collection<? extends Object> getDeprecatedBookNo();

    /**
     * Checks if the class has a deprecatedBookNo property value.<p>
     * 
     * @return true if there is a deprecatedBookNo property value.
     */
    boolean hasDeprecatedBookNo();

    /**
     * Adds a deprecatedBookNo property value.<p>
     * 
     * @param newDeprecatedBookNo the deprecatedBookNo property value to be added
     */
    void addDeprecatedBookNo(Object newDeprecatedBookNo);

    /**
     * Removes a deprecatedBookNo property value.<p>
     * 
     * @param oldDeprecatedBookNo the deprecatedBookNo property value to be removed.
     */
    void removeDeprecatedBookNo(Object oldDeprecatedBookNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#deprecatedHadithNo
     */
     
    /**
     * Gets all property values for the deprecatedHadithNo property.<p>
     * 
     * @returns a collection of values for the deprecatedHadithNo property.
     */
    Collection<? extends Object> getDeprecatedHadithNo();

    /**
     * Checks if the class has a deprecatedHadithNo property value.<p>
     * 
     * @return true if there is a deprecatedHadithNo property value.
     */
    boolean hasDeprecatedHadithNo();

    /**
     * Adds a deprecatedHadithNo property value.<p>
     * 
     * @param newDeprecatedHadithNo the deprecatedHadithNo property value to be added
     */
    void addDeprecatedHadithNo(Object newDeprecatedHadithNo);

    /**
     * Removes a deprecatedHadithNo property value.<p>
     * 
     * @param oldDeprecatedHadithNo the deprecatedHadithNo property value to be removed.
     */
    void removeDeprecatedHadithNo(Object oldDeprecatedHadithNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#endingHadithNo
     */
     
    /**
     * Gets all property values for the endingHadithNo property.<p>
     * 
     * @returns a collection of values for the endingHadithNo property.
     */
    Collection<? extends Object> getEndingHadithNo();

    /**
     * Checks if the class has a endingHadithNo property value.<p>
     * 
     * @return true if there is a endingHadithNo property value.
     */
    boolean hasEndingHadithNo();

    /**
     * Adds a endingHadithNo property value.<p>
     * 
     * @param newEndingHadithNo the endingHadithNo property value to be added
     */
    void addEndingHadithNo(Object newEndingHadithNo);

    /**
     * Removes a endingHadithNo property value.<p>
     * 
     * @param oldEndingHadithNo the endingHadithNo property value to be removed.
     */
    void removeEndingHadithNo(Object oldEndingHadithNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#fullHadith
     */
     
    /**
     * Gets all property values for the fullHadith property.<p>
     * 
     * @returns a collection of values for the fullHadith property.
     */
    Collection<? extends Object> getFullHadith();

    /**
     * Checks if the class has a fullHadith property value.<p>
     * 
     * @return true if there is a fullHadith property value.
     */
    boolean hasFullHadith();

    /**
     * Adds a fullHadith property value.<p>
     * 
     * @param newFullHadith the fullHadith property value to be added
     */
    void addFullHadith(Object newFullHadith);

    /**
     * Removes a fullHadith property value.<p>
     * 
     * @param oldFullHadith the fullHadith property value to be removed.
     */
    void removeFullHadith(Object oldFullHadith);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookNo
     */
     
    /**
     * Gets all property values for the hadithBookNo property.<p>
     * 
     * @returns a collection of values for the hadithBookNo property.
     */
    Collection<? extends Object> getHadithBookNo();

    /**
     * Checks if the class has a hadithBookNo property value.<p>
     * 
     * @return true if there is a hadithBookNo property value.
     */
    boolean hasHadithBookNo();

    /**
     * Adds a hadithBookNo property value.<p>
     * 
     * @param newHadithBookNo the hadithBookNo property value to be added
     */
    void addHadithBookNo(Object newHadithBookNo);

    /**
     * Removes a hadithBookNo property value.<p>
     * 
     * @param oldHadithBookNo the hadithBookNo property value to be removed.
     */
    void removeHadithBookNo(Object oldHadithBookNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookUrl
     */
     
    /**
     * Gets all property values for the hadithBookUrl property.<p>
     * 
     * @returns a collection of values for the hadithBookUrl property.
     */
    Collection<? extends Object> getHadithBookUrl();

    /**
     * Checks if the class has a hadithBookUrl property value.<p>
     * 
     * @return true if there is a hadithBookUrl property value.
     */
    boolean hasHadithBookUrl();

    /**
     * Adds a hadithBookUrl property value.<p>
     * 
     * @param newHadithBookUrl the hadithBookUrl property value to be added
     */
    void addHadithBookUrl(Object newHadithBookUrl);

    /**
     * Removes a hadithBookUrl property value.<p>
     * 
     * @param oldHadithBookUrl the hadithBookUrl property value to be removed.
     */
    void removeHadithBookUrl(Object oldHadithBookUrl);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithChapterIntro
     */
     
    /**
     * Gets all property values for the hadithChapterIntro property.<p>
     * 
     * @returns a collection of values for the hadithChapterIntro property.
     */
    Collection<? extends Object> getHadithChapterIntro();

    /**
     * Checks if the class has a hadithChapterIntro property value.<p>
     * 
     * @return true if there is a hadithChapterIntro property value.
     */
    boolean hasHadithChapterIntro();

    /**
     * Adds a hadithChapterIntro property value.<p>
     * 
     * @param newHadithChapterIntro the hadithChapterIntro property value to be added
     */
    void addHadithChapterIntro(Object newHadithChapterIntro);

    /**
     * Removes a hadithChapterIntro property value.<p>
     * 
     * @param oldHadithChapterIntro the hadithChapterIntro property value to be removed.
     */
    void removeHadithChapterIntro(Object oldHadithChapterIntro);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithChapterNo
     */
     
    /**
     * Gets all property values for the hadithChapterNo property.<p>
     * 
     * @returns a collection of values for the hadithChapterNo property.
     */
    Collection<? extends Object> getHadithChapterNo();

    /**
     * Checks if the class has a hadithChapterNo property value.<p>
     * 
     * @return true if there is a hadithChapterNo property value.
     */
    boolean hasHadithChapterNo();

    /**
     * Adds a hadithChapterNo property value.<p>
     * 
     * @param newHadithChapterNo the hadithChapterNo property value to be added
     */
    void addHadithChapterNo(Object newHadithChapterNo);

    /**
     * Removes a hadithChapterNo property value.<p>
     * 
     * @param oldHadithChapterNo the hadithChapterNo property value to be removed.
     */
    void removeHadithChapterNo(Object oldHadithChapterNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithNo
     */
     
    /**
     * Gets all property values for the hadithNo property.<p>
     * 
     * @returns a collection of values for the hadithNo property.
     */
    Collection<? extends Object> getHadithNo();

    /**
     * Checks if the class has a hadithNo property value.<p>
     * 
     * @return true if there is a hadithNo property value.
     */
    boolean hasHadithNo();

    /**
     * Adds a hadithNo property value.<p>
     * 
     * @param newHadithNo the hadithNo property value to be added
     */
    void addHadithNo(Object newHadithNo);

    /**
     * Removes a hadithNo property value.<p>
     * 
     * @param oldHadithNo the hadithNo property value to be removed.
     */
    void removeHadithNo(Object oldHadithNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithReferenceNo
     */
     
    /**
     * Gets all property values for the hadithReferenceNo property.<p>
     * 
     * @returns a collection of values for the hadithReferenceNo property.
     */
    Collection<? extends Object> getHadithReferenceNo();

    /**
     * Checks if the class has a hadithReferenceNo property value.<p>
     * 
     * @return true if there is a hadithReferenceNo property value.
     */
    boolean hasHadithReferenceNo();

    /**
     * Adds a hadithReferenceNo property value.<p>
     * 
     * @param newHadithReferenceNo the hadithReferenceNo property value to be added
     */
    void addHadithReferenceNo(Object newHadithReferenceNo);

    /**
     * Removes a hadithReferenceNo property value.<p>
     * 
     * @param oldHadithReferenceNo the hadithReferenceNo property value to be removed.
     */
    void removeHadithReferenceNo(Object oldHadithReferenceNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithText
     */
     
    /**
     * Gets all property values for the hadithText property.<p>
     * 
     * @returns a collection of values for the hadithText property.
     */
    Collection<? extends Object> getHadithText();

    /**
     * Checks if the class has a hadithText property value.<p>
     * 
     * @return true if there is a hadithText property value.
     */
    boolean hasHadithText();

    /**
     * Adds a hadithText property value.<p>
     * 
     * @param newHadithText the hadithText property value to be added
     */
    void addHadithText(Object newHadithText);

    /**
     * Removes a hadithText property value.<p>
     * 
     * @param oldHadithText the hadithText property value to be removed.
     */
    void removeHadithText(Object oldHadithText);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithUrl
     */
     
    /**
     * Gets all property values for the hadithUrl property.<p>
     * 
     * @returns a collection of values for the hadithUrl property.
     */
    Collection<? extends Object> getHadithUrl();

    /**
     * Checks if the class has a hadithUrl property value.<p>
     * 
     * @return true if there is a hadithUrl property value.
     */
    boolean hasHadithUrl();

    /**
     * Adds a hadithUrl property value.<p>
     * 
     * @param newHadithUrl the hadithUrl property value to be added
     */
    void addHadithUrl(Object newHadithUrl);

    /**
     * Removes a hadithUrl property value.<p>
     * 
     * @param oldHadithUrl the hadithUrl property value to be removed.
     */
    void removeHadithUrl(Object oldHadithUrl);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#hadithVolumeNo
     */
     
    /**
     * Gets all property values for the hadithVolumeNo property.<p>
     * 
     * @returns a collection of values for the hadithVolumeNo property.
     */
    Collection<? extends Object> getHadithVolumeNo();

    /**
     * Checks if the class has a hadithVolumeNo property value.<p>
     * 
     * @return true if there is a hadithVolumeNo property value.
     */
    boolean hasHadithVolumeNo();

    /**
     * Adds a hadithVolumeNo property value.<p>
     * 
     * @param newHadithVolumeNo the hadithVolumeNo property value to be added
     */
    void addHadithVolumeNo(Object newHadithVolumeNo);

    /**
     * Removes a hadithVolumeNo property value.<p>
     * 
     * @param oldHadithVolumeNo the hadithVolumeNo property value to be removed.
     */
    void removeHadithVolumeNo(Object oldHadithVolumeNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#inBookNo
     */
     
    /**
     * Gets all property values for the inBookNo property.<p>
     * 
     * @returns a collection of values for the inBookNo property.
     */
    Collection<? extends Object> getInBookNo();

    /**
     * Checks if the class has a inBookNo property value.<p>
     * 
     * @return true if there is a inBookNo property value.
     */
    boolean hasInBookNo();

    /**
     * Adds a inBookNo property value.<p>
     * 
     * @param newInBookNo the inBookNo property value to be added
     */
    void addInBookNo(Object newInBookNo);

    /**
     * Removes a inBookNo property value.<p>
     * 
     * @param oldInBookNo the inBookNo property value to be removed.
     */
    void removeInBookNo(Object oldInBookNo);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#narratorChain
     */
     
    /**
     * Gets all property values for the narratorChain property.<p>
     * 
     * @returns a collection of values for the narratorChain property.
     */
    Collection<? extends Object> getNarratorChain();

    /**
     * Checks if the class has a narratorChain property value.<p>
     * 
     * @return true if there is a narratorChain property value.
     */
    boolean hasNarratorChain();

    /**
     * Adds a narratorChain property value.<p>
     * 
     * @param newNarratorChain the narratorChain property value to be added
     */
    void addNarratorChain(Object newNarratorChain);

    /**
     * Removes a narratorChain property value.<p>
     * 
     * @param oldNarratorChain the narratorChain property value to be removed.
     */
    void removeNarratorChain(Object oldNarratorChain);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#sameAs
     */
     
    /**
     * Gets all property values for the sameAs property.<p>
     * 
     * @returns a collection of values for the sameAs property.
     */
    Collection<? extends Object> getSameAs();

    /**
     * Checks if the class has a sameAs property value.<p>
     * 
     * @return true if there is a sameAs property value.
     */
    boolean hasSameAs();

    /**
     * Adds a sameAs property value.<p>
     * 
     * @param newSameAs the sameAs property value to be added
     */
    void addSameAs(Object newSameAs);

    /**
     * Removes a sameAs property value.<p>
     * 
     * @param oldSameAs the sameAs property value to be removed.
     */
    void removeSameAs(Object oldSameAs);



    /* ***************************************************
     * Property http://www.lodislamica.me/ontology/hadithVoc#startingHadithNo
     */
     
    /**
     * Gets all property values for the startingHadithNo property.<p>
     * 
     * @returns a collection of values for the startingHadithNo property.
     */
    Collection<? extends Object> getStartingHadithNo();

    /**
     * Checks if the class has a startingHadithNo property value.<p>
     * 
     * @return true if there is a startingHadithNo property value.
     */
    boolean hasStartingHadithNo();

    /**
     * Adds a startingHadithNo property value.<p>
     * 
     * @param newStartingHadithNo the startingHadithNo property value to be added
     */
    void addStartingHadithNo(Object newStartingHadithNo);

    /**
     * Removes a startingHadithNo property value.<p>
     * 
     * @param oldStartingHadithNo the startingHadithNo property value to be removed.
     */
    void removeStartingHadithNo(Object oldStartingHadithNo);



    /* ***************************************************
     * Property https://www.w3.org/2000/01/rdf-schema#label
     */
     
    /**
     * Gets all property values for the label property.<p>
     * 
     * @returns a collection of values for the label property.
     */
    Collection<? extends Object> getLabel();

    /**
     * Checks if the class has a label property value.<p>
     * 
     * @return true if there is a label property value.
     */
    boolean hasLabel();

    /**
     * Adds a label property value.<p>
     * 
     * @param newLabel the label property value to be added
     */
    void addLabel(Object newLabel);

    /**
     * Removes a label property value.<p>
     * 
     * @param oldLabel the label property value to be removed.
     */
    void removeLabel(Object oldLabel);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
