package HadithRDFconvertor;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Mon Aug 08 23:13:09 PKT 2016 by Bushra
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://mlode.nlp2rdf.org/quranvocab#Verse
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VERSE.<p>
     * 
     */
    public static final OWLClass CLASS_VERSE = factory.getOWLClass(IRI.create("http://mlode.nlp2rdf.org/quranvocab#Verse"));

    /* ***************************************************
     * Class http://quranontology.com/Resource/City
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CITY.<p>
     * 
     */
    public static final OWLClass CLASS_CITY = factory.getOWLClass(IRI.create("http://quranontology.com/Resource/City"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Hadith
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITH.<p>
     * 
     */
    public static final OWLClass CLASS_HADITH = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Hadith"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithBook
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHBOOK.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHBOOK = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithBook"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithChapter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHCHAPTER.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHCHAPTER = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithChapter"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithCollection
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHCOLLECTION.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHCOLLECTION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithCollection"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithMatan
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHMATAN.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHMATAN = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithMatan"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithSanad
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHSANAD.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHSANAD = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithSanad"));

    /* ***************************************************
     * Object Property http://mlode.nlp2rdf.org/quranvocab#revelationPlace
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REVELATIONPLACE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REVELATIONPLACE = factory.getOWLObjectProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#revelationPlace"));

    /* ***************************************************
     * Object Property http://purl.org/dc/terms/hasPart
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPART.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPART = factory.getOWLObjectProperty(IRI.create("http://purl.org/dc/terms/hasPart"));

    /* ***************************************************
     * Object Property http://purl.org/dc/terms/isPartOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOF = factory.getOWLObjectProperty(IRI.create("http://purl.org/dc/terms/isPartOf"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/AllyTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ALLYTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ALLYTO = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/AllyTo"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/AncestorOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ANCESTOROF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ANCESTOROF = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/AncestorOf"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/BelongsInPeriod
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property BELONGSINPERIOD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BELONGSINPERIOD = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/BelongsInPeriod"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/BondWith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property BONDWITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BONDWITH = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/BondWith"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/Caused
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CAUSED.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CAUSED = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/Caused"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/ContainsLocation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINSLOCATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINSLOCATION = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/ContainsLocation"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/ContainsMentionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINSMENTIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINSMENTIONOF = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/ContainsMentionOf"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/ContemporaryWith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTEMPORARYWITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTEMPORARYWITH = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/ContemporaryWith"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/DiscussTopic
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DISCUSSTOPIC.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DISCUSSTOPIC = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/DiscussTopic"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/DiscussedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DISCUSSEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DISCUSSEDIN = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/DiscussedIn"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/EnemyWith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ENEMYWITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ENEMYWITH = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/EnemyWith"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/EventAtPeriod
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EVENTATPERIOD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EVENTATPERIOD = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/EventAtPeriod"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/EventAtPlace
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EVENTATPLACE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EVENTATPLACE = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/EventAtPlace"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/FamilyBondWith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FAMILYBONDWITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FAMILYBONDWITH = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/FamilyBondWith"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/Follows
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FOLLOWS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FOLLOWS = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/Follows"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/FriendOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FRIENDOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FRIENDOF = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/FriendOf"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/GrandParentOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property GRANDPARENTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_GRANDPARENTOF = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/GrandParentOf"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/HasAncestor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASANCESTOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASANCESTOR = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/HasAncestor"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/HasChild
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCHILD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCHILD = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/HasChild"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/HasGrandParent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASGRANDPARENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASGRANDPARENT = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/HasGrandParent"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/HasMember
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMEMBER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMEMBER = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/HasMember"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/HasParent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPARENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPARENT = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/HasParent"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/HasSibling
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSIBLING.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSIBLING = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/HasSibling"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/HasSpouse
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSPOUSE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSPOUSE = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/HasSpouse"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/HasSubTopic
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSUBTOPIC.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSUBTOPIC = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/HasSubTopic"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/Involves
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVOLVES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVOLVES = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/Involves"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/IsCausedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCAUSEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCAUSEDBY = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/IsCausedBy"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/IsFollowedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISFOLLOWEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISFOLLOWEDBY = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/IsFollowedBy"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/IsRelatedInEvent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISRELATEDINEVENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISRELATEDINEVENT = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/IsRelatedInEvent"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/LivedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LIVEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LIVEDIN = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/LivedIn"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/LocatedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LOCATEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LOCATEDIN = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/LocatedIn"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/MemberOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MEMBEROF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MEMBEROF = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/MemberOf"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/MentionedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MENTIONEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MENTIONEDIN = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/MentionedIn"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/PeriodHasEvent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PERIODHASEVENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PERIODHASEVENT = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/PeriodHasEvent"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/PeriodHasPerson
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PERIODHASPERSON.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PERIODHASPERSON = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/PeriodHasPerson"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/PlaceHasEvent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PLACEHASEVENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PLACEHASEVENT = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/PlaceHasEvent"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/ReferTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REFERTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REFERTO = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/ReferTo"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/ReferToVerse
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REFERTOVERSE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REFERTOVERSE = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/ReferToVerse"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/RevealedAfter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REVEALEDAFTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REVEALEDAFTER = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/RevealedAfter"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/RevealedBefore
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REVEALEDBEFORE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REVEALEDBEFORE = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/RevealedBefore"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/SimilarVerse
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SIMILARVERSE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SIMILARVERSE = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/SimilarVerse"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/SlightlySimilar
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SLIGHTLYSIMILAR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SLIGHTLYSIMILAR = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/SlightlySimilar"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/StronglySimilar
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property STRONGLYSIMILAR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_STRONGLYSIMILAR = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/StronglySimilar"));

    /* ***************************************************
     * Object Property http://quranontology.com/Resource/SubTopicOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SUBTOPICOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SUBTOPICOF = factory.getOWLObjectProperty(IRI.create("http://quranontology.com/Resource/SubTopicOf"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#chapterIndex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHAPTERINDEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHAPTERINDEX = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#chapterIndex"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#chapterName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHAPTERNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHAPTERNAME = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#chapterName"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#chapterOrder
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHAPTERORDER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHAPTERORDER = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#chapterOrder"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#descByJalalayn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DESCBYJALALAYN.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DESCBYJALALAYN = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#descByJalalayn"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#descByMuyasser
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DESCBYMUYASSER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DESCBYMUYASSER = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#descByMuyasser"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#hasSajdaType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSAJDATYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSAJDATYPE = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#hasSajdaType"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#inPage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INPAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INPAGE = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#inPage"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#inPart
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INPART.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INPART = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#inPart"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#inQuarter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INQUARTER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INQUARTER = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#inQuarter"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#inSection
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INSECTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INSECTION = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#inSection"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#inStation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INSTATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INSTATION = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#inStation"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#lexicalItemIndex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LEXICALITEMINDEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LEXICALITEMINDEX = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#lexicalItemIndex"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#sectionsCount
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SECTIONSCOUNT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SECTIONSCOUNT = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#sectionsCount"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#startOfPageNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STARTOFPAGENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STARTOFPAGENO = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#startOfPageNo"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#startOfPartNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STARTOFPARTNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STARTOFPARTNO = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#startOfPartNo"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#startOfQuarterNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STARTOFQUARTERNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STARTOFQUARTERNO = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#startOfQuarterNo"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#startOfSectionNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STARTOFSECTIONNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STARTOFSECTIONNO = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#startOfSectionNo"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#startOfStationNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STARTOFSTATIONNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STARTOFSTATIONNO = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#startOfStationNo"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#verseCount
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VERSECOUNT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VERSECOUNT = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#verseCount"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#verseIndex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VERSEINDEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VERSEINDEX = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#verseIndex"));

    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#wordIndex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WORDINDEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WORDINDEX = factory.getOWLDataProperty(IRI.create("http://mlode.nlp2rdf.org/quranvocab#wordIndex"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/DisplayOrder
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DISPLAYORDER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DISPLAYORDER = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/DisplayOrder"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/DisplayText
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DISPLAYTEXT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DISPLAYTEXT = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/DisplayText"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/Duration
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DURATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DURATION = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/Duration"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/HasSajda
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSAJDA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSAJDA = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/HasSajda"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/InHizb
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INHIZB.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INHIZB = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/InHizb"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/InRukus
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INRUKUS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INRUKUS = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/InRukus"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/IndividualsCount
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INDIVIDUALSCOUNT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INDIVIDUALSCOUNT = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/IndividualsCount"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/RevelationOrder
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property REVELATIONORDER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_REVELATIONORDER = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/RevelationOrder"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/RukusCount
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RUKUSCOUNT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RUKUSCOUNT = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/RukusCount"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/TopicCompleteName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOPICCOMPLETENAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TOPICCOMPLETENAME = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/TopicCompleteName"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/VerseAbsoluteIndex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VERSEABSOLUTEINDEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VERSEABSOLUTEINDEX = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/VerseAbsoluteIndex"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/WordLemma
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WORDLEMMA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WORDLEMMA = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/WordLemma"));

    /* ***************************************************
     * Data Property http://quranontology.com/Resource/WordRoot
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WORDROOT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WORDROOT = factory.getOWLDataProperty(IRI.create("http://quranontology.com/Resource/WordRoot"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#collectionName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COLLECTIONNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COLLECTIONNAME = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#collectionName"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#deprecatedBookNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEPRECATEDBOOKNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEPRECATEDBOOKNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#deprecatedBookNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#deprecatedHadithNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEPRECATEDHADITHNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEPRECATEDHADITHNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#deprecatedHadithNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#endingHadithNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENDINGHADITHNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENDINGHADITHNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#endingHadithNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#fullHadith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FULLHADITH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FULLHADITH = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#fullHadith"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHBOOKNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHBOOKNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithBookNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookUrl
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHBOOKURL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHBOOKURL = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithBookUrl"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithChapterIntro
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHCHAPTERINTRO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHCHAPTERINTRO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithChapterIntro"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithChapterNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHCHAPTERNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHCHAPTERNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithChapterNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithReferenceNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHREFERENCENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHREFERENCENO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithReferenceNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithText
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHTEXT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHTEXT = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithText"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithUrl
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHURL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHURL = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithUrl"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithVolumeNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHVOLUMENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHVOLUMENO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithVolumeNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#inBookNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INBOOKNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INBOOKNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#inBookNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#narratorChain
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NARRATORCHAIN.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NARRATORCHAIN = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#narratorChain"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#sameAs
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SAMEAS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SAMEAS = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#sameAs"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#startingHadithNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STARTINGHADITHNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STARTINGHADITHNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#startingHadithNo"));

    /* ***************************************************
     * Data Property https://www.w3.org/2000/01/rdf-schema#label
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LABEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LABEL = factory.getOWLDataProperty(IRI.create("https://www.w3.org/2000/01/rdf-schema#label"));


}
