package HadithOnto.impl;

import HadithOnto.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultDivineLocation <br>
 * @version generated on Thu Jan 10 15:59:46 PKT 2019 by Bushra
 */
public class DefaultDivineLocation extends WrappedIndividualImpl implements DivineLocation {

    public DefaultDivineLocation(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://quranontology.com/Resource/mentionedIn
     */
     
    public Collection<? extends Hadith> getMentionedIn() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_MENTIONEDIN,
                                               DefaultHadith.class);
    }

    public boolean hasMentionedIn() {
	   return !getMentionedIn().isEmpty();
    }

    public void addMentionedIn(Hadith newMentionedIn) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_MENTIONEDIN,
                                       newMentionedIn);
    }

    public void removeMentionedIn(Hadith oldMentionedIn) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_MENTIONEDIN,
                                          oldMentionedIn);
    }


    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#assertedBy
     */
     
    public Collection<? extends WrappedIndividual> getAssertedBy() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ASSERTEDBY,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasAssertedBy() {
	   return !getAssertedBy().isEmpty();
    }

    public void addAssertedBy(WrappedIndividual newAssertedBy) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ASSERTEDBY,
                                       newAssertedBy);
    }

    public void removeAssertedBy(WrappedIndividual oldAssertedBy) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ASSERTEDBY,
                                          oldAssertedBy);
    }


    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#asserts
     */
     
    public Collection<? extends WrappedIndividual> getAsserts() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ASSERTS,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasAsserts() {
	   return !getAsserts().isEmpty();
    }

    public void addAsserts(WrappedIndividual newAsserts) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ASSERTS,
                                       newAsserts);
    }

    public void removeAsserts(WrappedIndividual oldAsserts) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ASSERTS,
                                          oldAsserts);
    }


    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#authored
     */
     
    public Collection<? extends WrappedIndividual> getAuthored() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_AUTHORED,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasAuthored() {
	   return !getAuthored().isEmpty();
    }

    public void addAuthored(WrappedIndividual newAuthored) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_AUTHORED,
                                       newAuthored);
    }

    public void removeAuthored(WrappedIndividual oldAuthored) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_AUTHORED,
                                          oldAuthored);
    }


    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#authoredBy
     */
     
    public Collection<? extends WrappedIndividual> getAuthoredBy() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_AUTHOREDBY,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasAuthoredBy() {
	   return !getAuthoredBy().isEmpty();
    }

    public void addAuthoredBy(WrappedIndividual newAuthoredBy) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_AUTHOREDBY,
                                       newAuthoredBy);
    }

    public void removeAuthoredBy(WrappedIndividual oldAuthoredBy) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_AUTHOREDBY,
                                          oldAuthoredBy);
    }


    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#happenedIn
     */
     
    public Collection<? extends WrappedIndividual> getHappenedIn() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAPPENEDIN,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHappenedIn() {
	   return !getHappenedIn().isEmpty();
    }

    public void addHappenedIn(WrappedIndividual newHappenedIn) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAPPENEDIN,
                                       newHappenedIn);
    }

    public void removeHappenedIn(WrappedIndividual oldHappenedIn) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAPPENEDIN,
                                          oldHappenedIn);
    }


    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasPart
     */
     
    public Collection<? extends WrappedIndividual> getHasPart() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASPART,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasPart() {
	   return !getHasPart().isEmpty();
    }

    public void addHasPart(WrappedIndividual newHasPart) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASPART,
                                       newHasPart);
    }

    public void removeHasPart(WrappedIndividual oldHasPart) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASPART,
                                          oldHasPart);
    }


    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#involvedIn
     */
     
    public Collection<? extends WrappedIndividual> getInvolvedIn() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_INVOLVEDIN,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasInvolvedIn() {
	   return !getInvolvedIn().isEmpty();
    }

    public void addInvolvedIn(WrappedIndividual newInvolvedIn) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_INVOLVEDIN,
                                       newInvolvedIn);
    }

    public void removeInvolvedIn(WrappedIndividual oldInvolvedIn) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_INVOLVEDIN,
                                          oldInvolvedIn);
    }


    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#isPartOf
     */
     
    public Collection<? extends WrappedIndividual> getIsPartOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISPARTOF,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasIsPartOf() {
	   return !getIsPartOf().isEmpty();
    }

    public void addIsPartOf(WrappedIndividual newIsPartOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISPARTOF,
                                       newIsPartOf);
    }

    public void removeIsPartOf(WrappedIndividual oldIsPartOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISPARTOF,
                                          oldIsPartOf);
    }


    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#participatedIn
     */
     
    public Collection<? extends WrappedIndividual> getParticipatedIn() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_PARTICIPATEDIN,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasParticipatedIn() {
	   return !getParticipatedIn().isEmpty();
    }

    public void addParticipatedIn(WrappedIndividual newParticipatedIn) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_PARTICIPATEDIN,
                                       newParticipatedIn);
    }

    public void removeParticipatedIn(WrappedIndividual oldParticipatedIn) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_PARTICIPATEDIN,
                                          oldParticipatedIn);
    }


    /* ***************************************************
     * Object Property https://www.w3.org/1999/02/22-rdf-syntax-ns#seeAlso
     */
     
    public Collection<? extends WrappedIndividual> getSeeAlso() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_SEEALSO,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasSeeAlso() {
	   return !getSeeAlso().isEmpty();
    }

    public void addSeeAlso(WrappedIndividual newSeeAlso) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_SEEALSO,
                                       newSeeAlso);
    }

    public void removeSeeAlso(WrappedIndividual oldSeeAlso) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_SEEALSO,
                                          oldSeeAlso);
    }


    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#chapterIndex
     */
     
    public Collection<? extends Object> getChapterIndex() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CHAPTERINDEX, Object.class);
    }

    public boolean hasChapterIndex() {
		return !getChapterIndex().isEmpty();
    }

    public void addChapterIndex(Object newChapterIndex) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CHAPTERINDEX, newChapterIndex);
    }

    public void removeChapterIndex(Object oldChapterIndex) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CHAPTERINDEX, oldChapterIndex);
    }


    /* ***************************************************
     * Data Property http://mlode.nlp2rdf.org/quranvocab#verseIndex
     */
     
    public Collection<? extends Object> getVerseIndex() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_VERSEINDEX, Object.class);
    }

    public boolean hasVerseIndex() {
		return !getVerseIndex().isEmpty();
    }

    public void addVerseIndex(Object newVerseIndex) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_VERSEINDEX, newVerseIndex);
    }

    public void removeVerseIndex(Object oldVerseIndex) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_VERSEINDEX, oldVerseIndex);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#akhtalatTadlees
     */
     
    public Collection<? extends Object> getAkhtalatTadlees() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_AKHTALATTADLEES, Object.class);
    }

    public boolean hasAkhtalatTadlees() {
		return !getAkhtalatTadlees().isEmpty();
    }

    public void addAkhtalatTadlees(Object newAkhtalatTadlees) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_AKHTALATTADLEES, newAkhtalatTadlees);
    }

    public void removeAkhtalatTadlees(Object oldAkhtalatTadlees) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_AKHTALATTADLEES, oldAkhtalatTadlees);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#alAqama
     */
     
    public Collection<? extends Object> getAlAqama() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ALAQAMA, Object.class);
    }

    public boolean hasAlAqama() {
		return !getAlAqama().isEmpty();
    }

    public void addAlAqama(Object newAlAqama) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ALAQAMA, newAlAqama);
    }

    public void removeAlAqama(Object oldAlAqama) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ALAQAMA, oldAlAqama);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#alMawali
     */
     
    public Collection<? extends Object> getAlMawali() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ALMAWALI, Object.class);
    }

    public boolean hasAlMawali() {
		return !getAlMawali().isEmpty();
    }

    public void addAlMawali(Object newAlMawali) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ALMAWALI, newAlMawali);
    }

    public void removeAlMawali(Object oldAlMawali) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ALMAWALI, oldAlMawali);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#anNishat
     */
     
    public Collection<? extends Object> getAnNishat() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ANNISHAT, Object.class);
    }

    public boolean hasAnNishat() {
		return !getAnNishat().isEmpty();
    }

    public void addAnNishat(Object newAnNishat) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ANNISHAT, newAnNishat);
    }

    public void removeAnNishat(Object oldAnNishat) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ANNISHAT, oldAnNishat);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#baladAlWafat
     */
     
    public Collection<? extends Object> getBaladAlWafat() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BALADALWAFAT, Object.class);
    }

    public boolean hasBaladAlWafat() {
		return !getBaladAlWafat().isEmpty();
    }

    public void addBaladAlWafat(Object newBaladAlWafat) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BALADALWAFAT, newBaladAlWafat);
    }

    public void removeBaladAlWafat(Object oldBaladAlWafat) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BALADALWAFAT, oldBaladAlWafat);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#chapterTarjama
     */
     
    public Collection<? extends Object> getChapterTarjama() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CHAPTERTARJAMA, Object.class);
    }

    public boolean hasChapterTarjama() {
		return !getChapterTarjama().isEmpty();
    }

    public void addChapterTarjama(Object newChapterTarjama) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CHAPTERTARJAMA, newChapterTarjama);
    }

    public void removeChapterTarjama(Object oldChapterTarjama) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CHAPTERTARJAMA, oldChapterTarjama);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#collectionName
     */
     
    public Collection<? extends Object> getCollectionName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COLLECTIONNAME, Object.class);
    }

    public boolean hasCollectionName() {
		return !getCollectionName().isEmpty();
    }

    public void addCollectionName(Object newCollectionName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COLLECTIONNAME, newCollectionName);
    }

    public void removeCollectionName(Object oldCollectionName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COLLECTIONNAME, oldCollectionName);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#date
     */
     
    public Collection<? extends Object> getDate() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DATE, Object.class);
    }

    public boolean hasDate() {
		return !getDate().isEmpty();
    }

    public void addDate(Object newDate) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DATE, newDate);
    }

    public void removeDate(Object oldDate) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DATE, oldDate);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#deprecatedHadithNo
     */
     
    public Collection<? extends Object> getDeprecatedHadithNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEPRECATEDHADITHNO, Object.class);
    }

    public boolean hasDeprecatedHadithNo() {
		return !getDeprecatedHadithNo().isEmpty();
    }

    public void addDeprecatedHadithNo(Object newDeprecatedHadithNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEPRECATEDHADITHNO, newDeprecatedHadithNo);
    }

    public void removeDeprecatedHadithNo(Object oldDeprecatedHadithNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEPRECATEDHADITHNO, oldDeprecatedHadithNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#eBookNo
     */
     
    public Collection<? extends Object> getEBookNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_EBOOKNO, Object.class);
    }

    public boolean hasEBookNo() {
		return !getEBookNo().isEmpty();
    }

    public void addEBookNo(Object newEBookNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_EBOOKNO, newEBookNo);
    }

    public void removeEBookNo(Object oldEBookNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_EBOOKNO, oldEBookNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#eHadithNo
     */
     
    public Collection<? extends Object> getEHadithNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_EHADITHNO, Object.class);
    }

    public boolean hasEHadithNo() {
		return !getEHadithNo().isEmpty();
    }

    public void addEHadithNo(Object newEHadithNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_EHADITHNO, newEHadithNo);
    }

    public void removeEHadithNo(Object oldEHadithNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_EHADITHNO, oldEHadithNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#eVolNo
     */
     
    public Collection<? extends Object> getEVolNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_EVOLNO, Object.class);
    }

    public boolean hasEVolNo() {
		return !getEVolNo().isEmpty();
    }

    public void addEVolNo(Object newEVolNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_EVOLNO, newEVolNo);
    }

    public void removeEVolNo(Object oldEVolNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_EVOLNO, oldEVolNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#endingHadithNo
     */
     
    public Collection<? extends Object> getEndingHadithNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENDINGHADITHNO, Object.class);
    }

    public boolean hasEndingHadithNo() {
		return !getEndingHadithNo().isEmpty();
    }

    public void addEndingHadithNo(Object newEndingHadithNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENDINGHADITHNO, newEndingHadithNo);
    }

    public void removeEndingHadithNo(Object oldEndingHadithNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENDINGHADITHNO, oldEndingHadithNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#englishReference
     */
     
    public Collection<? extends Object> getEnglishReference() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGLISHREFERENCE, Object.class);
    }

    public boolean hasEnglishReference() {
		return !getEnglishReference().isEmpty();
    }

    public void addEnglishReference(Object newEnglishReference) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGLISHREFERENCE, newEnglishReference);
    }

    public void removeEnglishReference(Object oldEnglishReference) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGLISHREFERENCE, oldEnglishReference);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#firstChar
     */
     
    public Collection<? extends Object> getFirstChar() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FIRSTCHAR, Object.class);
    }

    public boolean hasFirstChar() {
		return !getFirstChar().isEmpty();
    }

    public void addFirstChar(Object newFirstChar) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FIRSTCHAR, newFirstChar);
    }

    public void removeFirstChar(Object oldFirstChar) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FIRSTCHAR, oldFirstChar);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#fullHadith
     */
     
    public Collection<? extends Object> getFullHadith() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FULLHADITH, Object.class);
    }

    public boolean hasFullHadith() {
		return !getFullHadith().isEmpty();
    }

    public void addFullHadith(Object newFullHadith) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FULLHADITH, newFullHadith);
    }

    public void removeFullHadith(Object oldFullHadith) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FULLHADITH, oldFullHadith);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookIntro
     */
     
    public Collection<? extends Object> getHadithBookIntro() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKINTRO, Object.class);
    }

    public boolean hasHadithBookIntro() {
		return !getHadithBookIntro().isEmpty();
    }

    public void addHadithBookIntro(Object newHadithBookIntro) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKINTRO, newHadithBookIntro);
    }

    public void removeHadithBookIntro(Object oldHadithBookIntro) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKINTRO, oldHadithBookIntro);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookNo
     */
     
    public Collection<? extends Object> getHadithBookNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKNO, Object.class);
    }

    public boolean hasHadithBookNo() {
		return !getHadithBookNo().isEmpty();
    }

    public void addHadithBookNo(Object newHadithBookNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKNO, newHadithBookNo);
    }

    public void removeHadithBookNo(Object oldHadithBookNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKNO, oldHadithBookNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookUrl
     */
     
    public Collection<? extends Object> getHadithBookUrl() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKURL, Object.class);
    }

    public boolean hasHadithBookUrl() {
		return !getHadithBookUrl().isEmpty();
    }

    public void addHadithBookUrl(Object newHadithBookUrl) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKURL, newHadithBookUrl);
    }

    public void removeHadithBookUrl(Object oldHadithBookUrl) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKURL, oldHadithBookUrl);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithChapterNo
     */
     
    public Collection<? extends Object> getHadithChapterNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHCHAPTERNO, Object.class);
    }

    public boolean hasHadithChapterNo() {
		return !getHadithChapterNo().isEmpty();
    }

    public void addHadithChapterNo(Object newHadithChapterNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHCHAPTERNO, newHadithChapterNo);
    }

    public void removeHadithChapterNo(Object oldHadithChapterNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHCHAPTERNO, oldHadithChapterNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithNo
     */
     
    public Collection<? extends Object> getHadithNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHNO, Object.class);
    }

    public boolean hasHadithNo() {
		return !getHadithNo().isEmpty();
    }

    public void addHadithNo(Object newHadithNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHNO, newHadithNo);
    }

    public void removeHadithNo(Object oldHadithNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHNO, oldHadithNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithReferenceNo
     */
     
    public Collection<? extends Object> getHadithReferenceNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHREFERENCENO, Object.class);
    }

    public boolean hasHadithReferenceNo() {
		return !getHadithReferenceNo().isEmpty();
    }

    public void addHadithReferenceNo(Object newHadithReferenceNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHREFERENCENO, newHadithReferenceNo);
    }

    public void removeHadithReferenceNo(Object oldHadithReferenceNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHREFERENCENO, oldHadithReferenceNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithRepetition
     */
     
    public Collection<? extends Object> getHadithRepetition() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHREPETITION, Object.class);
    }

    public boolean hasHadithRepetition() {
		return !getHadithRepetition().isEmpty();
    }

    public void addHadithRepetition(Object newHadithRepetition) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHREPETITION, newHadithRepetition);
    }

    public void removeHadithRepetition(Object oldHadithRepetition) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHREPETITION, oldHadithRepetition);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithText
     */
     
    public Collection<? extends Object> getHadithText() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHTEXT, Object.class);
    }

    public boolean hasHadithText() {
		return !getHadithText().isEmpty();
    }

    public void addHadithText(Object newHadithText) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHTEXT, newHadithText);
    }

    public void removeHadithText(Object oldHadithText) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHTEXT, oldHadithText);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithType
     */
     
    public Collection<? extends Object> getHadithType() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHTYPE, Object.class);
    }

    public boolean hasHadithType() {
		return !getHadithType().isEmpty();
    }

    public void addHadithType(Object newHadithType) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHTYPE, newHadithType);
    }

    public void removeHadithType(Object oldHadithType) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHTYPE, oldHadithType);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithUrl
     */
     
    public Collection<? extends Object> getHadithUrl() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHURL, Object.class);
    }

    public boolean hasHadithUrl() {
		return !getHadithUrl().isEmpty();
    }

    public void addHadithUrl(Object newHadithUrl) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHURL, newHadithUrl);
    }

    public void removeHadithUrl(Object oldHadithUrl) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHURL, oldHadithUrl);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithVolumeNo
     */
     
    public Collection<? extends Object> getHadithVolumeNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHVOLUMENO, Object.class);
    }

    public boolean hasHadithVolumeNo() {
		return !getHadithVolumeNo().isEmpty();
    }

    public void addHadithVolumeNo(Object newHadithVolumeNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHVOLUMENO, newHadithVolumeNo);
    }

    public void removeHadithVolumeNo(Object oldHadithVolumeNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHVOLUMENO, oldHadithVolumeNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#inBookNo
     */
     
    public Collection<? extends Object> getInBookNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INBOOKNO, Object.class);
    }

    public boolean hasInBookNo() {
		return !getInBookNo().isEmpty();
    }

    public void addInBookNo(Object newInBookNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INBOOKNO, newInBookNo);
    }

    public void removeInBookNo(Object oldInBookNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INBOOKNO, oldInBookNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#ismArRavi
     */
     
    public Collection<? extends Object> getIsmArRavi() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ISMARRAVI, Object.class);
    }

    public boolean hasIsmArRavi() {
		return !getIsmArRavi().isEmpty();
    }

    public void addIsmArRavi(Object newIsmArRavi) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ISMARRAVI, newIsmArRavi);
    }

    public void removeIsmArRavi(Object oldIsmArRavi) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ISMARRAVI, oldIsmArRavi);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#ismAsSuhra
     */
     
    public Collection<? extends Object> getIsmAsSuhra() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ISMASSUHRA, Object.class);
    }

    public boolean hasIsmAsSuhra() {
		return !getIsmAsSuhra().isEmpty();
    }

    public void addIsmAsSuhra(Object newIsmAsSuhra) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ISMASSUHRA, newIsmAsSuhra);
    }

    public void removeIsmAsSuhra(Object oldIsmAsSuhra) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ISMASSUHRA, oldIsmAsSuhra);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#kunyat
     */
     
    public Collection<? extends Object> getKunyat() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_KUNYAT, Object.class);
    }

    public boolean hasKunyat() {
		return !getKunyat().isEmpty();
    }

    public void addKunyat(Object newKunyat) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_KUNYAT, newKunyat);
    }

    public void removeKunyat(Object oldKunyat) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_KUNYAT, oldKunyat);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#laqab
     */
     
    public Collection<? extends Object> getLaqab() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LAQAB, Object.class);
    }

    public boolean hasLaqab() {
		return !getLaqab().isEmpty();
    }

    public void addLaqab(Object newLaqab) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LAQAB, newLaqab);
    }

    public void removeLaqab(Object oldLaqab) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LAQAB, oldLaqab);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#mazhab
     */
     
    public Collection<? extends Object> getMazhab() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MAZHAB, Object.class);
    }

    public boolean hasMazhab() {
		return !getMazhab().isEmpty();
    }

    public void addMazhab(Object newMazhab) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MAZHAB, newMazhab);
    }

    public void removeMazhab(Object oldMazhab) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MAZHAB, oldMazhab);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#name
     */
     
    public Collection<? extends Object> getName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NAME, Object.class);
    }

    public boolean hasName() {
		return !getName().isEmpty();
    }

    public void addName(Object newName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NAME, newName);
    }

    public void removeName(Object oldName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NAME, oldName);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#narratorChain
     */
     
    public Collection<? extends Object> getNarratorChain() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NARRATORCHAIN, Object.class);
    }

    public boolean hasNarratorChain() {
		return !getNarratorChain().isEmpty();
    }

    public void addNarratorChain(Object newNarratorChain) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NARRATORCHAIN, newNarratorChain);
    }

    public void removeNarratorChain(Object oldNarratorChain) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NARRATORCHAIN, oldNarratorChain);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#nasab
     */
     
    public Collection<? extends Object> getNasab() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NASAB, Object.class);
    }

    public boolean hasNasab() {
		return !getNasab().isEmpty();
    }

    public void addNasab(Object newNasab) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NASAB, newNasab);
    }

    public void removeNasab(Object oldNasab) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NASAB, oldNasab);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#raqamArRavi
     */
     
    public Collection<? extends Object> getRaqamArRavi() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RAQAMARRAVI, Object.class);
    }

    public boolean hasRaqamArRavi() {
		return !getRaqamArRavi().isEmpty();
    }

    public void addRaqamArRavi(Object newRaqamArRavi) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RAQAMARRAVI, newRaqamArRavi);
    }

    public void removeRaqamArRavi(Object oldRaqamArRavi) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RAQAMARRAVI, oldRaqamArRavi);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#rutba
     */
     
    public Collection<? extends Object> getRutba() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RUTBA, Object.class);
    }

    public boolean hasRutba() {
		return !getRutba().isEmpty();
    }

    public void addRutba(Object newRutba) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RUTBA, newRutba);
    }

    public void removeRutba(Object oldRutba) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RUTBA, oldRutba);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#sameAs
     */
     
    public Collection<? extends Object> getSameAs() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SAMEAS, Object.class);
    }

    public boolean hasSameAs() {
		return !getSameAs().isEmpty();
    }

    public void addSameAs(Object newSameAs) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SAMEAS, newSameAs);
    }

    public void removeSameAs(Object oldSameAs) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SAMEAS, oldSameAs);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#sequenceNo
     */
     
    public Collection<? extends Object> getSequenceNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SEQUENCENO, Object.class);
    }

    public boolean hasSequenceNo() {
		return !getSequenceNo().isEmpty();
    }

    public void addSequenceNo(Object newSequenceNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SEQUENCENO, newSequenceNo);
    }

    public void removeSequenceNo(Object oldSequenceNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SEQUENCENO, oldSequenceNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#startingHadithNo
     */
     
    public Collection<? extends Object> getStartingHadithNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STARTINGHADITHNO, Object.class);
    }

    public boolean hasStartingHadithNo() {
		return !getStartingHadithNo().isEmpty();
    }

    public void addStartingHadithNo(Object newStartingHadithNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STARTINGHADITHNO, newStartingHadithNo);
    }

    public void removeStartingHadithNo(Object oldStartingHadithNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STARTINGHADITHNO, oldStartingHadithNo);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#sunAlMilad
     */
     
    public Collection<? extends Object> getSunAlMilad() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SUNALMILAD, Object.class);
    }

    public boolean hasSunAlMilad() {
		return !getSunAlMilad().isEmpty();
    }

    public void addSunAlMilad(Object newSunAlMilad) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SUNALMILAD, newSunAlMilad);
    }

    public void removeSunAlMilad(Object oldSunAlMilad) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SUNALMILAD, oldSunAlMilad);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#sunAlWafat
     */
     
    public Collection<? extends Object> getSunAlWafat() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SUNALWAFAT, Object.class);
    }

    public boolean hasSunAlWafat() {
		return !getSunAlWafat().isEmpty();
    }

    public void addSunAlWafat(Object newSunAlWafat) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SUNALWAFAT, newSunAlWafat);
    }

    public void removeSunAlWafat(Object oldSunAlWafat) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SUNALWAFAT, oldSunAlWafat);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#taqba
     */
     
    public Collection<? extends Object> getTaqba() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TAQBA, Object.class);
    }

    public boolean hasTaqba() {
		return !getTaqba().isEmpty();
    }

    public void addTaqba(Object newTaqba) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TAQBA, newTaqba);
    }

    public void removeTaqba(Object oldTaqba) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TAQBA, oldTaqba);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#totalHadithInchapter
     */
     
    public Collection<? extends Object> getTotalHadithInchapter() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOTALHADITHINCHAPTER, Object.class);
    }

    public boolean hasTotalHadithInchapter() {
		return !getTotalHadithInchapter().isEmpty();
    }

    public void addTotalHadithInchapter(Object newTotalHadithInchapter) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOTALHADITHINCHAPTER, newTotalHadithInchapter);
    }

    public void removeTotalHadithInchapter(Object oldTotalHadithInchapter) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOTALHADITHINCHAPTER, oldTotalHadithInchapter);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#totalSubChapters
     */
     
    public Collection<? extends Object> getTotalSubChapters() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOTALSUBCHAPTERS, Object.class);
    }

    public boolean hasTotalSubChapters() {
		return !getTotalSubChapters().isEmpty();
    }

    public void addTotalSubChapters(Object newTotalSubChapters) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOTALSUBCHAPTERS, newTotalSubChapters);
    }

    public void removeTotalSubChapters(Object oldTotalSubChapters) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOTALSUBCHAPTERS, oldTotalSubChapters);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#ummarArRavi
     */
     
    public Collection<? extends Object> getUmmarArRavi() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UMMARARRAVI, Object.class);
    }

    public boolean hasUmmarArRavi() {
		return !getUmmarArRavi().isEmpty();
    }

    public void addUmmarArRavi(Object newUmmarArRavi) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UMMARARRAVI, newUmmarArRavi);
    }

    public void removeUmmarArRavi(Object oldUmmarArRavi) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UMMARARRAVI, oldUmmarArRavi);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#wasaf
     */
     
    public Collection<? extends Object> getWasaf() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_WASAF, Object.class);
    }

    public boolean hasWasaf() {
		return !getWasaf().isEmpty();
    }

    public void addWasaf(Object newWasaf) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_WASAF, newWasaf);
    }

    public void removeWasaf(Object oldWasaf) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_WASAF, oldWasaf);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc##gradedBy
     */
     
    public Collection<? extends Object> getGradedBy() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GRADEDBY, Object.class);
    }

    public boolean hasGradedBy() {
		return !getGradedBy().isEmpty();
    }

    public void addGradedBy(Object newGradedBy) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GRADEDBY, newGradedBy);
    }

    public void removeGradedBy(Object oldGradedBy) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GRADEDBY, oldGradedBy);
    }


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc##hadithGrade
     */
     
    public Collection<? extends Object> getHadithGrade() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHGRADE, Object.class);
    }

    public boolean hasHadithGrade() {
		return !getHadithGrade().isEmpty();
    }

    public void addHadithGrade(Object newHadithGrade) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHGRADE, newHadithGrade);
    }

    public void removeHadithGrade(Object oldHadithGrade) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHGRADE, oldHadithGrade);
    }


    /* ***************************************************
     * Data Property https://www.w3.org/2000/01/rdf-schema#label
     */
     
    public Collection<? extends Object> getLabel() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LABEL, Object.class);
    }

    public boolean hasLabel() {
		return !getLabel().isEmpty();
    }

    public void addLabel(Object newLabel) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LABEL, newLabel);
    }

    public void removeLabel(Object oldLabel) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LABEL, oldLabel);
    }


}
